# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.signatures.utils

defmodule Dspy.Signatures.Utils do
  @moduledoc """
  Submodule bindings for `dspy.signatures.utils`.
  """

  def __snakebridge_python_name__, do: "dspy.signatures.utils"
  def __snakebridge_library__, do: "dspy"

  @doc """

  """
  @spec get_dspy_field_type(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_dspy_field_type(field, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :get_dspy_field_type, [field], opts)
  end
end
