# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy
# Python class: ColBERTv2

defmodule Dspy.ColBERTv2 do
  @moduledoc """
  Wrapper for the ColBERTv2 Retrieval.
  """
  def __snakebridge_python_name__, do: "dspy"
  def __snakebridge_python_class__, do: "ColBERTv2"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `url` (String.t() default: 'http://0.0.0.0')
  - `port` ((String.t() | integer()) | nil default: None)
  - `post_requests` (boolean() default: False)
  """
  @spec new() :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), (String.t() | integer()) | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), (String.t() | integer()) | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), (String.t() | integer()) | nil, boolean()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), (String.t() | integer()) | nil, boolean(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new() do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], [])
  end

  def new(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  def new(url) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [url], [])
  end

  def new(url, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [url], opts)
  end

  def new(url, port) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [url, port], [])
  end

  def new(url, port, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [url, port], opts)
  end

  def new(url, port, post_requests) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [url, port, post_requests], [])
  end

  def new(url, port, post_requests, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [url, port, post_requests], opts)
  end
end
