# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy
# Python class: Completions

defmodule Dspy.Completions do
  @moduledoc """
  Wrapper for Python class Completions.
  """
  def __snakebridge_python_name__, do: "dspy"
  def __snakebridge_python_class__, do: "Completions"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `list_or_dict` (term())
  - `signature` (term() default: None)
  """
  @spec new(term(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(list_or_dict, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [list_or_dict] ++ List.wrap(args), opts)
  end

  @doc """
  Python method `Completions.items`.

  ## Returns

  - `term()`
  """
  @spec items(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def items(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :items, [], opts)
  end
end
