# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy
# Python class: LMUnsupportedFeatureError

defmodule Dspy.LMUnsupportedFeatureError do
  @moduledoc """
  The LM, provider, or DSPy provider wrapper does not support a requested feature.



  ## Parameters

  - `message` - Human-readable error message.
  - `feature` - One unsupported setting path reported by the engine.
  - `features` - Feature names that were requested but unavailable, such as `"finetuning"`, `"reinforce"`, or `"structured_outputs"`.
  - `issues` - Optional detailed reasons the requested feature could not be used. **kwargs: Structured error metadata accepted by `DSPyError`.
  """
  def __snakebridge_python_name__, do: "dspy"
  def __snakebridge_python_class__, do: "LMUnsupportedFeatureError"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `message` (String.t() default: '')
  - `features` (list(String.t()) | nil keyword-only default: None)
  - `feature` (String.t() | nil keyword-only default: None)
  - `issues` (list(String.t()) | nil keyword-only default: None)
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Add a note to the exception

  ## Parameters

  - `note` (term())

  ## Returns

  - `term()`
  """
  @spec add_note(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def add_note(ref, note, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :add_note, [note], opts)
  end

  @doc """
  Set self.__traceback__ to tb and return self.

  ## Parameters

  - `tb` (term())

  ## Returns

  - `term()`
  """
  @spec with_traceback(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def with_traceback(ref, tb, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :with_traceback, [tb], opts)
  end

  @spec args(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def args(ref) do
    SnakeBridge.Runtime.get_attr(ref, :args)
  end

  @spec default_code(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def default_code(ref) do
    SnakeBridge.Runtime.get_attr(ref, :default_code)
  end
end
