# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.adapters.types.image

defmodule Dspy.Adapters.Types.Image do
  @moduledoc """
  Submodule bindings for `dspy.adapters.types.image`.
  """

  def __snakebridge_python_name__, do: "dspy.adapters.types.image"
  def __snakebridge_library__, do: "dspy"

  @doc """
  Encode an image or file to a base64 data URI.



  ## Parameters

  - `image` - The image or file to encode. Can be a PIL Image, file path, URL, or data URI.
  - `download_images` - Whether to download images from URLs.

  ## Returns

  Returns `String.t()`. The data URI of the file or the URL if download_images is False.

  ## Raises

  - `ArgumentError` - If the file type is not supported.

  Parameters:
  - `image` (((String.t() | binary()) | term()) | %{optional(term()) => term()})
  - `download_images` (boolean() default: False)

  Returns:
  - `String.t()`
  """
  @spec encode_image(((String.t() | binary()) | term()) | %{optional(term()) => term()}) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  @spec encode_image(
          ((String.t() | binary()) | term()) | %{optional(term()) => term()},
          keyword()
        ) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  @spec encode_image(
          ((String.t() | binary()) | term()) | %{optional(term()) => term()},
          boolean()
        ) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  @spec encode_image(
          ((String.t() | binary()) | term()) | %{optional(term()) => term()},
          boolean(),
          keyword()
        ) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def encode_image(image) do
    SnakeBridge.Runtime.call(__MODULE__, :encode_image, [image], [])
  end

  def encode_image(image, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :encode_image, [image], opts)
  end

  def encode_image(image, download_images) do
    SnakeBridge.Runtime.call(__MODULE__, :encode_image, [image, download_images], [])
  end

  def encode_image(image, download_images, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :encode_image, [image, download_images], opts)
  end

  @doc """
  Check if the object is an image or a valid media file reference.

  Parameters:
  - `obj` (term())

  Returns:
  - `boolean()`
  """
  @spec is_image(term(), keyword()) :: {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def is_image(obj, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :is_image, [obj], opts)
  end

  @doc """
  Check if a string is a valid URL.

  Parameters:
  - `string` (String.t())

  Returns:
  - `boolean()`
  """
  @spec is_url(String.t(), keyword()) :: {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def is_url(string, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :is_url, [string], opts)
  end
end
