# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.utils.parallelizer

defmodule Dspy.Utils.Parallelizer do
  @moduledoc """
  Submodule bindings for `dspy.utils.parallelizer`.
  """

  def __snakebridge_python_name__, do: "dspy.utils.parallelizer"
  def __snakebridge_library__, do: "dspy"
end
