# Generated by SnakeBridge v0.14.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt.grpo
# Python class: GRPO

defmodule Dspy.Teleprompt.GRPO do
  @moduledoc """
  Wrapper for Python class GRPO.
  """
  def __snakebridge_python_name__, do: "dspy.teleprompt.grpo"
  def __snakebridge_python_class__, do: "GRPO"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `metric` (term() | nil default: None)
  - `multitask` (boolean() default: True)
  - `train_kwargs` (term() default: None)
  - `adapter` (term() default: None)
  - `exclude_demos` (boolean() default: False)
  - `num_threads` (integer() default: 6)
  - `num_train_steps` (integer() default: 100)
  - `seed` (integer() default: 0)
  - `num_dspy_examples_per_grpo_step` (integer() default: 1)
  - `num_rollouts_per_grpo_step` (integer() default: 1)
  - `use_train_as_val` (boolean() default: False)
  - `num_steps_for_val` (integer() default: 5)
  - `report_train_scores` (boolean() default: False)
  - `failure_score` (float() default: 0)
  - `format_failure_score` (float() default: -1)
  - `variably_invoked_predictor_grouping_mode` ((term() | term()) | term() default: 'truncate')
  - `variably_invoked_predictor_fill_strategy` ((term() | term()) | nil default: None)
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Optimize the student program.



  ## Parameters

  - `student` - The student program to optimize.
  - `trainset` - The training set to use for optimization.
  - `teacher` - The teacher program to use for optimization.
  - `valset` - The validation set to use for optimization.

  ## Returns

  - `Dspy.Primitives.ModuleClass3.t()`
  """
  @spec compile(
          SnakeBridge.Ref.t(),
          Dspy.Primitives.ModuleClass3.t(),
          list(Dspy.Primitives.ExampleClass.t()),
          list(term()),
          keyword()
        ) :: {:ok, Dspy.Primitives.ModuleClass3.t()} | {:error, Snakepit.Error.t()}
  def compile(ref, student, trainset, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :compile, [student, trainset] ++ List.wrap(args), opts)
  end

  @doc """
  Python method `GRPO.convert_to_lm_dict`.

  ## Parameters

  - `arg` (term())

  ## Returns

  - `%{optional(Dspy.Clients.LM.t()) => term()}`
  """
  @spec convert_to_lm_dict(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, %{optional(Dspy.Clients.LM.t()) => term()}} | {:error, Snakepit.Error.t()}
  def convert_to_lm_dict(ref, arg, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :convert_to_lm_dict, [arg], opts)
  end

  @doc """
  Get the parameters of the teleprompter.

  ## Returns

  - `%{optional(String.t()) => term()}`
  """
  @spec get_params(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, %{optional(String.t()) => term()}} | {:error, Snakepit.Error.t()}
  def get_params(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_params, [], opts)
  end

  @doc """
  Python method `GRPO.report_validation_metrics`.

  ## Parameters

  - `student` (term())
  - `trainset` (term())
  - `valset` (term())
  - `logger` (term())
  - `step_idx` (term() default: -1)

  ## Returns

  - `term()`
  """
  @spec report_validation_metrics(
          SnakeBridge.Ref.t(),
          term(),
          term(),
          term(),
          term(),
          list(term()),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def report_validation_metrics(ref, student, trainset, valset, logger, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_method(
      ref,
      :report_validation_metrics,
      [student, trainset, valset, logger] ++ List.wrap(args),
      opts
    )
  end

  @doc """
  Python method `GRPO.select_training_sample_and_update_shuffled_trainset`.

  ## Parameters

  - `original_trainset` (list(Dspy.Primitives.ExampleClass.t()))
  - `train_step_idx` (integer())

  ## Returns

  - `list(Dspy.Primitives.ExampleClass.t())`
  """
  @spec select_training_sample_and_update_shuffled_trainset(
          SnakeBridge.Ref.t(),
          list(Dspy.Primitives.ExampleClass.t()),
          integer(),
          keyword()
        ) :: {:ok, list(Dspy.Primitives.ExampleClass.t())} | {:error, Snakepit.Error.t()}
  def select_training_sample_and_update_shuffled_trainset(
        ref,
        original_trainset,
        train_step_idx,
        opts \\ []
      ) do
    SnakeBridge.Runtime.call_method(
      ref,
      :select_training_sample_and_update_shuffled_trainset,
      [original_trainset, train_step_idx],
      opts
    )
  end

  @doc """
  Python method `GRPO.update_shuffled_trainset`.

  ## Parameters

  - `original_trainset` (term())

  ## Returns

  - `term()`
  """
  @spec update_shuffled_trainset(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def update_shuffled_trainset(ref, original_trainset, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :update_shuffled_trainset, [original_trainset], opts)
  end

  @doc """
  Python method `GRPO.validate_trace_data_and_log_issues`.

  ## Parameters

  - `trace_data` (list(list(list(%{optional(String.t()) => term()}))))
  - `subsample_training_dataset` (list(Dspy.Primitives.ExampleClass.t()))
  - `num_teachers` (integer())
  - `num_samples_per_input` (integer())
  - `pred_signature_hash_to_ind` (%{optional(integer()) => integer()})

  ## Returns

  - `term()`
  """
  @spec validate_trace_data_and_log_issues(
          SnakeBridge.Ref.t(),
          list(list(list(%{optional(String.t()) => term()}))),
          list(Dspy.Primitives.ExampleClass.t()),
          integer(),
          integer(),
          %{optional(integer()) => integer()},
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def validate_trace_data_and_log_issues(
        ref,
        trace_data,
        subsample_training_dataset,
        num_teachers,
        num_samples_per_input,
        pred_signature_hash_to_ind,
        opts \\ []
      ) do
    SnakeBridge.Runtime.call_method(
      ref,
      :validate_trace_data_and_log_issues,
      [
        trace_data,
        subsample_training_dataset,
        num_teachers,
        num_samples_per_input,
        pred_signature_hash_to_ind
      ],
      opts
    )
  end
end
