# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt.grpo
# Python class: GRPO

defmodule Dspy.Teleprompt.GRPO do
  def __snakebridge_python_name__, do: "dspy.teleprompt.grpo"
  def __snakebridge_python_class__, do: "GRPO"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @spec compile(
          SnakeBridge.Ref.t(),
          Dspy.Primitives.Module.Module.t(),
          list(Dspy.Primitives.Example.t()),
          list(term()),
          keyword()
        ) :: {:ok, Dspy.Primitives.Module.Module.t()} | {:error, Snakepit.Error.t()}
  def compile(ref, student, trainset, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :compile, [student, trainset] ++ List.wrap(args), opts)
  end

  @spec convert_to_lm_dict(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, %{optional(Dspy.Clients.LMClass.t()) => term()}} | {:error, Snakepit.Error.t()}
  def convert_to_lm_dict(ref, arg, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :convert_to_lm_dict, [arg], opts)
  end

  @spec get_params(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, %{optional(String.t()) => term()}} | {:error, Snakepit.Error.t()}
  def get_params(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_params, [], opts)
  end

  @spec report_validation_metrics(
          SnakeBridge.Ref.t(),
          term(),
          term(),
          term(),
          term(),
          list(term()),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def report_validation_metrics(ref, student, trainset, valset, logger, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_method(
      ref,
      :report_validation_metrics,
      [student, trainset, valset, logger] ++ List.wrap(args),
      opts
    )
  end

  @spec select_training_sample_and_update_shuffled_trainset(
          SnakeBridge.Ref.t(),
          list(Dspy.Primitives.Example.t()),
          integer(),
          keyword()
        ) :: {:ok, list(Dspy.Primitives.Example.t())} | {:error, Snakepit.Error.t()}
  def select_training_sample_and_update_shuffled_trainset(
        ref,
        original_trainset,
        train_step_idx,
        opts \\ []
      ) do
    SnakeBridge.Runtime.call_method(
      ref,
      :select_training_sample_and_update_shuffled_trainset,
      [original_trainset, train_step_idx],
      opts
    )
  end

  @spec update_shuffled_trainset(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def update_shuffled_trainset(ref, original_trainset, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :update_shuffled_trainset, [original_trainset], opts)
  end

  @spec validate_trace_data_and_log_issues(
          SnakeBridge.Ref.t(),
          list(list(list(%{optional(String.t()) => term()}))),
          list(Dspy.Primitives.Example.t()),
          integer(),
          integer(),
          %{optional(integer()) => integer()},
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def validate_trace_data_and_log_issues(
        ref,
        trace_data,
        subsample_training_dataset,
        num_teachers,
        num_samples_per_input,
        pred_signature_hash_to_ind,
        opts \\ []
      ) do
    SnakeBridge.Runtime.call_method(
      ref,
      :validate_trace_data_and_log_issues,
      [
        trace_data,
        subsample_training_dataset,
        num_teachers,
        num_samples_per_input,
        pred_signature_hash_to_ind
      ],
      opts
    )
  end
end
