# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.clients.provider

defmodule Dspy.Clients.Provider.Module do
  @moduledoc """
  Submodule bindings for `dspy.clients.provider`.
  """

  def __snakebridge_python_name__, do: "dspy.clients.provider"
  def __snakebridge_library__, do: "dspy"
end
