# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt.copro_optimizer

defmodule Dspy.Teleprompt.CoproOptimizer do
  @moduledoc """
  Submodule bindings for `dspy.teleprompt.copro_optimizer`.
  """

  def __snakebridge_python_name__, do: "dspy.teleprompt.copro_optimizer"
  def __snakebridge_library__, do: "dspy"
end
