# Generated by SnakeBridge v0.15.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.streaming
# Python class: StreamResponse

defmodule Dspy.Streaming.StreamResponse do
  @moduledoc """
  StreamResponse(predict_name: str, signature_field_name: str, chunk: str, is_last_chunk: bool)
  """
  def __snakebridge_python_name__, do: "dspy.streaming"
  def __snakebridge_python_class__, do: "StreamResponse"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `predict_name` (String.t())
  - `signature_field_name` (String.t())
  - `chunk` (String.t())
  - `is_last_chunk` (boolean())
  """
  @spec new(String.t(), String.t(), String.t(), boolean(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(predict_name, signature_field_name, chunk, is_last_chunk, opts \\ []) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [predict_name, signature_field_name, chunk, is_last_chunk],
      opts
    )
  end
end
