# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt.infer_rules

defmodule Dspy.Teleprompt.InferRules.Module do
  @moduledoc """
  Submodule bindings for `dspy.teleprompt.infer_rules`.
  """

  def __snakebridge_python_name__, do: "dspy.teleprompt.infer_rules"
  def __snakebridge_library__, do: "dspy"
end
