# Generated by SnakeBridge v0.13.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt.gepa.gepa_utils
# Python class: LoggerAdapter

defmodule Dspy.Teleprompt.Gepa.GepaUtils.LoggerAdapter do
  @moduledoc """
  Wrapper for Python class LoggerAdapter.
  """
  def __snakebridge_python_name__, do: "dspy.teleprompt.gepa.gepa_utils"
  def __snakebridge_python_class__, do: "LoggerAdapter"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `logger` (term())
  """
  @spec new(term(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(logger, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [logger], opts)
  end

  @doc """
  Python method `LoggerAdapter.log`.

  ## Parameters

  - `x` (String.t())

  ## Returns

  - `term()`
  """
  @spec log(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def log(ref, x, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :log, [x], opts)
  end
end
