# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.primitives.sandbox_serializable

defmodule Dspy.Primitives.SandboxSerializable.Module do
  @moduledoc """
  Abstract base class for RLM sandbox-serializable types.

  Types that subclass :class:`SandboxSerializable` can be injected into the
  REPL environment used by :class:`dspy.RLM`. Subclasses implement four
  abstract methods describing how a value enters and appears inside the
  sandbox, and inherit:

  - `__get_pydantic_core_schema__` so the type can be used directly as a
    :class:`dspy.Signature` field annotation (see "The pydantic hook" below).
  - `to_repl_variable()` as a default helper that delegates to the free
    :func:`build_repl_variable` function.

  The free function :func:`build_repl_variable` is also exported for the rare
  case where you need to wrap a value without subclassing.

  The pydantic hook
  -----------------

  `__get_pydantic_core_schema__` lets subclasses be used as
  `dspy.Signature` field annotations. It is a pass-through (no validation,
  `str()` serialization) — RLM owns real serialization via `to_sandbox()`
  and `sandbox_assignment()`.

  ## Version

  - Requested: 3.4.0
  - Observed at generation: 3.4.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Dspy.Primitives.SandboxSerializable.Module.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Dspy.Primitives.SandboxSerializable.Module.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Dspy.Primitives.SandboxSerializable.Module.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Dspy.Primitives.SandboxSerializable.Module.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "dspy.primitives.sandbox_serializable"
  @doc false
  def __snakebridge_library__, do: "dspy"

  @doc """
  Build a :class:`REPLVariable` for a SandboxSerializable value.

  Free function form of :meth:`SandboxSerializable.to_repl_variable`. Use
  it when you need to wrap a value imperatively without going through the
  method on the instance. The resulting variable's preview comes from
  `rlm_preview()`; `sandbox_setup()` imports are appended to the
  description so the model learns which names are bound in the sandbox
  before it writes code.

  ## Parameters

  - `obj` (term())
  - `name` (term())
  - `field_info` (term())

  ## Returns

  - `term()`
  """
  @spec build_repl_variable(term(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def build_repl_variable(obj, name, field_info, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :build_repl_variable, [obj, name, field_info], opts)
  end
end
