# Generated by SnakeBridge v0.14.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.dsp.colbertv2
# Python class: ColBERTv2

defmodule Dspy.Dsp.Colbertv2.ColBERTv2 do
  @moduledoc """
  Wrapper for the ColBERTv2 Retrieval.
  """
  def __snakebridge_python_name__, do: "dspy.dsp.colbertv2"
  def __snakebridge_python_class__, do: "ColBERTv2"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `url` (String.t() default: 'http://0.0.0.0')
  - `port` (term() default: None)
  - `post_requests` (boolean() default: False)
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end
end
