# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.streaming.streaming_listener

defmodule Dspy.Streaming.StreamingListener do
  @moduledoc """
  Submodule bindings for `dspy.streaming.streaming_listener`.
  """

  def __snakebridge_python_name__, do: "dspy.streaming.streaming_listener"
  def __snakebridge_library__, do: "dspy"

  @doc """
  Find the predictor for each stream listener.

  This is a utility function to automatically find the predictor for each stream listener. It is used when some
  listeners don't specify the predictor they want to listen to. If a listener's `signature_field_name` is not
  unique in the program, this function will raise an error.

  Parameters:
  - `program` (term())
  - `stream_listeners` (list(Dspy.Streaming.StreamingListener.StreamListener.t()))

  Returns:
  - `%{optional(integer()) => list(Dspy.Streaming.StreamingListener.StreamListener.t())}`
  """
  @spec find_predictor_for_stream_listeners(
          term(),
          list(Dspy.Streaming.StreamingListener.StreamListener.t()),
          keyword()
        ) ::
          {:ok,
           %{optional(integer()) => list(Dspy.Streaming.StreamingListener.StreamListener.t())}}
          | {:error, Snakepit.Error.t()}
  def find_predictor_for_stream_listeners(program, stream_listeners, opts \\ []) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :find_predictor_for_stream_listeners,
      [program, stream_listeners],
      opts
    )
  end
end
