# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.adapters.two_step_adapter

defmodule Dspy.Adapters.TwoStepAdapter.Module do
  @moduledoc """
  Submodule bindings for `dspy.adapters.two_step_adapter`.
  """

  def __snakebridge_python_name__, do: "dspy.adapters.two_step_adapter"
  def __snakebridge_library__, do: "dspy"
end
