# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.utils.usage_tracker

defmodule Dspy.Utils.UsageTracker do
  @moduledoc """
  Submodule bindings for `dspy.utils.usage_tracker`.
  """

  def __snakebridge_python_name__, do: "dspy.utils.usage_tracker"
  def __snakebridge_library__, do: "dspy"

  @doc """
  Context manager for tracking LM usage.

  Returns:
  - `term()`
  """
  @spec track_usage(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def track_usage(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :track_usage, [], opts)
  end
end
