# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.utils.dummies

defmodule Dspy.Utils.Dummies do
  @moduledoc """
  Submodule bindings for `dspy.utils.dummies`.
  """

  def __snakebridge_python_name__, do: "dspy.utils.dummies"
  def __snakebridge_library__, do: "dspy"

  @doc """

  """
  @spec dummy_rm() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec dummy_rm(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec dummy_rm(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec dummy_rm(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dummy_rm() do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [], [])
  end

  def dummy_rm(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [], opts)
  end

  def dummy_rm(passages) do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [passages], [])
  end

  def dummy_rm(passages, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [passages], opts)
  end
end
