# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15

defmodule Dspy.Lm15 do
  @moduledoc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Version

  - Requested: 3.4.0
  - Observed at generation: 3.4.0

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Dspy.Lm15.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Dspy.Lm15.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Dspy.Lm15.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Dspy.Lm15.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "dspy.lm15"
  @doc false
  def __snakebridge_library__, do: "dspy"

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec adaptation_policy(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def adaptation_policy(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "AdaptationPolicy", [], opts)
  end

  @doc """
  Async mirror of :func:`materialize_response`.

  ## Parameters

  - `events` (term())
  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec amaterialize_response(term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def amaterialize_response(events, request, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :amaterialize_response, [events, request], opts)
  end

  @doc """
  A choice judgment property: `{key: description-or-None}` or a list of keys.

  ## Parameters

  - `instruction` (String.t())
  - `options` (term() | term())

  ## Returns

  - `%{
  optional(String.t()) =>
    (((((nil | boolean()) | integer()) | float()) | String.t())
     | list(
         (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
         | %{optional(String.t()) => term()}
       ))
    | %{
        optional(String.t()) =>
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()}
      }
  }`
  """
  @spec choice(String.t(), term() | term(), keyword()) ::
          {:ok,
           %{
             optional(String.t()) =>
               (((((nil | boolean()) | integer()) | float()) | String.t())
                | list(
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                  ))
               | %{
                   optional(String.t()) =>
                     (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                     | %{optional(String.t()) => term()}
                 }
           }}
          | {:error, Snakepit.Error.t()}
  def choice(instruction, options, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :choice, [instruction, options], opts)
  end

  @doc """
  Create a data part (structured input, or a judged answer).

  ## Parameters

  - `value` ((((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
  | %{optional(String.t()) => term()})
  - `probabilities` (%{optional(String.t()) => %{optional(String.t()) => float()}} | nil keyword-only default: None)
  - `method` (term() | nil keyword-only default: None)
  - `continuation` ((term() | term()) | nil keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec data(
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()},
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def data(value, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :data, [value], opts)
  end

  @doc """
  Derive a FunctionTool from *fn* with a full, typed account.

  Like :func:`tool`, but returns the :class:`ToolDerivation` so users can
  inspect exactly how each parameter was mapped (explainability parity
  with the explain() ethos). `tool(fn)` is sugar for `derive(fn).tool`.

  ## Parameters

  - `py_fn` (term())
  - `name` (String.t() | nil keyword-only default: None)
  - `description` (String.t() | nil keyword-only default: None)
  - `config` (term() keyword-only default: ToolConfig(docstring_style='auto', include_defaults=True, additional_properties_false=False, overrides=()))

  ## Returns

  - `term()`
  """
  @spec derive_tool(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def derive_tool(py_fn, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :derive_tool, [py_fn], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec error_code(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def error_code(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "ErrorCode", [], opts)
  end

  @doc """
  Python module attribute `dspy.lm15.ERROR_CODES`.

  ## Returns

  - `MapSet.t(term())`
  """
  @spec error_codes() :: {:ok, MapSet.t(term())} | {:error, Snakepit.Error.t()}
  def error_codes() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "ERROR_CODES")
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec finish_reason(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def finish_reason(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "FinishReason", [], opts)
  end

  @doc """
  Python module attribute `dspy.lm15.FINISH_REASONS`.

  ## Returns

  - `MapSet.t(term())`
  """
  @spec finish_reasons() :: {:ok, MapSet.t(term())} | {:error, Snakepit.Error.t()}
  def finish_reasons() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "FINISH_REASONS")
  end

  @doc """
  A `response_format` declaring the given judgment properties.

  ## Parameters

  - `name` (String.t() keyword-only default: 'judgments')
  - `strict` (boolean() keyword-only default: True)
  - `properties` (%{
  optional(String.t()) =>
    (((((nil | boolean()) | integer()) | float()) | String.t())
     | list(
         (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
         | %{optional(String.t()) => term()}
       ))
    | %{
        optional(String.t()) =>
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()}
      }
  })

  ## Returns

  - `%{
  optional(String.t()) =>
    (((((nil | boolean()) | integer()) | float()) | String.t())
     | list(
         (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
         | %{optional(String.t()) => term()}
       ))
    | %{
        optional(String.t()) =>
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()}
      }
  }`
  """
  @spec judgments(keyword()) ::
          {:ok,
           %{
             optional(String.t()) =>
               (((((nil | boolean()) | integer()) | float()) | String.t())
                | list(
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                  ))
               | %{
                   optional(String.t()) =>
                     (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                     | %{optional(String.t()) => term()}
                 }
           }}
          | {:error, Snakepit.Error.t()}
  def judgments(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :judgments, [], opts)
  end

  @doc """
  Consume a complete stream, requiring a final end event and closing its source.

  ## Parameters

  - `events` (term())
  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec materialize_response(term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def materialize_response(events, request, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :materialize_response, [events, request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec part_type(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def part_type(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "PartType", [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec reasoning_effort(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def reasoning_effort(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "ReasoningEffort", [], opts)
  end

  @doc """
  Declare a provider for the native `dspy.LM`s constructed after this call.

  `definition` is an lm15 `ProviderDefinition` (`ProviderDefinition.chat(access,
  compat=...)` for an OpenAI-compatible server). Afterwards
  `dspy.LM("<id>/<model>")` — and every alias — routes natively with the
  LM's `api_key`, `api_base` and `timeout` honored, and the provider's
  own key variable read when none is given. A call the native route cannot
  carry falls back to LiteLLM at the declared address with the same
  credential, never at an address LiteLLM knows by a similar name.

  `metadata_namespaces` names the snapshot namespaces (LiteLLM's
  spellings, e.g. `("fireworks_ai",)`) whose entries may describe and
  price this provider's models. Give it only when the endpoint really is
  that service; nothing is inherited from an alias. `supports` states
  model support for the whole provider and `models` per model id; a
  snapshot entry, when one is found, is the more specific fact and wins.

  Registering the same definition again with the same statements is a
  no-op. A different registration under the same id is refused unless
  `replace=True`, and even then only LMs constructed afterwards bind it.
  A spelling another registered provider, lm15's registry or LiteLLM
  already uses is always refused.

  ## Parameters

  - `definition` (term())
  - `supports` (Dspy.Lm15.ModelSupport.t() | nil keyword-only default: None)
  - `models` (term() | nil keyword-only default: None)
  - `metadata_namespaces` ({String.t(), term()} keyword-only default: ())
  - `replace` (boolean() keyword-only default: False)

  ## Returns

  - `Dspy.Lm15.RegisteredProvider.t()`
  """
  @spec register_provider(term(), keyword()) ::
          {:ok, Dspy.Lm15.RegisteredProvider.t()} | {:error, Snakepit.Error.t()}
  def register_provider(definition, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :register_provider, [definition], opts)
  end

  @doc """
  The providers registered in this process, in registration order —

  the tuple a `dspy.LM` binds when constructed.

  ## Returns

  - `{Dspy.Lm15.RegisteredProvider.t(), term()}`
  """
  @spec registered_providers(keyword()) ::
          {:ok, {Dspy.Lm15.RegisteredProvider.t(), term()}} | {:error, Snakepit.Error.t()}
  def registered_providers(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :registered_providers, [], opts)
  end

  @doc """
  A Chat Completions request body → the canonical :class:`Request` (MAP-12).

  `body` is the JSON object a client would POST to `/chat/completions`
  (`model`, `messages`, `tools`, generation knobs).  `compat` names
  the server dialect whose spellings are read — a preset name
  (`"openai"`, `"groq"`, `"deepseek"`, …), an
  :class:`OpenAIChatCompat`, or None for OpenAI's own — the same policy
  :class:`OpenAIChatLM` writes with, so what that adapter emits for a
  Request reads back as that Request wherever the wire can carry it.

  Every key has one verdict: it maps to a canonical field, it passes
  verbatim through `config.extensions` (`seed`, `logit_bias`,
  `presence_penalty`, `frequency_penalty`, `metadata`, …), or it is
  refused with :class:`UnsupportedFeatureError` naming the key (`n`,
  the deprecated `functions` shape, a content block with no part, a
  spelling another server owns).  `stream` / `stream_options` are
  call-mode keys with no place on a Request and are read and dropped.
  Malformed input raises `ValueError` / `TypeError`.

  On the adapter, `lm.request_from_openai_chat(body)` is the same
  function under that adapter's compat, including its per-model overrides.

  ## Parameters

  - `body` (term())
  - `compat` ((term() | String.t()) | nil keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec request_from_openai_chat(term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def request_from_openai_chat(body, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :request_from_openai_chat, [body], opts)
  end

  @doc """
  A Chat Completions response body → the canonical :class:`Response`.

  The reading-side twin of :func:`request_from_openai_chat`: `body` is
  the JSON object a Chat Completions server (or a client library that
  imitates one — litellm's `ModelResponse.model_dump()`) returned.  It
  is the same reader :meth:`OpenAIChatLM.parse_response` runs on provider
  traffic, so what it maps (text, `reasoning_content` → thinking, tool
  calls, refusal, usage, logprobs, finish reason) and what it records as
  unmapped (`provider_data["_lm15_unmapped"]`) are pinned by the
  contract's `response` direction.  An error envelope raises the typed
  provider error.

  `model` fills `Response.model` when the body carries none.
  `choice` names the choice to read; left unset, a body with more than
  one choice is refused (a Response is one message; read each choice by
  index instead) — the twin of the request side's refusal of `n`.
  Keys the reader does not know are neither refused nor lost: the whole
  body is `provider_data`.  No compat is taken: the Chat Completions
  response shape does not vary by server the way the request does.

  ## Parameters

  - `body` (term())
  - `model` (String.t() | nil keyword-only default: None)
  - `choice` (integer() | nil keyword-only default: None)
  - `response_format` (term() | nil keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec response_from_openai_chat(term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def response_from_openai_chat(body, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :response_from_openai_chat, [body], opts)
  end

  @doc """
  Convert a complete Response to stream events.

  The conversion is intentionally lossless for the Delta vocabulary.  If a
  response contains a valid Part that has no Delta representation, this
  function raises instead of silently dropping content.

  ## Parameters

  - `response` (term())

  ## Returns

  - `term()`
  """
  @spec response_to_events(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def response_to_events(response, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :response_to_events, [response], opts)
  end

  @doc """
  Python module attribute `dspy.lm15.RETRYABLE_ERRORS`.

  ## Returns

  - `tuple()`
  """
  @spec retryable_errors() :: {:ok, tuple()} | {:error, Snakepit.Error.t()}
  def retryable_errors() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "RETRYABLE_ERRORS")
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec role(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def role(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "Role", [], opts)
  end

  @doc """
  Python module attribute `dspy.lm15.ROLE_VALUES`.

  ## Returns

  - `MapSet.t(term())`
  """
  @spec role_values() :: {:ok, MapSet.t(term())} | {:error, Snakepit.Error.t()}
  def role_values() do
    SnakeBridge.Runtime.get_module_attr(__MODULE__, "ROLE_VALUES")
  end

  @doc """
  An ordered judgment: levels low → high; `{name: description}` or descriptions.

  ## Parameters

  - `instruction` (String.t())
  - `levels` (term() | term())

  ## Returns

  - `%{
  optional(String.t()) =>
    (((((nil | boolean()) | integer()) | float()) | String.t())
     | list(
         (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
         | %{optional(String.t()) => term()}
       ))
    | %{
        optional(String.t()) =>
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()}
      }
  }`
  """
  @spec score(String.t(), term() | term(), keyword()) ::
          {:ok,
           %{
             optional(String.t()) =>
               (((((nil | boolean()) | integer()) | float()) | String.t())
                | list(
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                  ))
               | %{
                   optional(String.t()) =>
                     (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                     | %{optional(String.t()) => term()}
                 }
           }}
          | {:error, Snakepit.Error.t()}
  def score(instruction, levels, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :score, [instruction, levels], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec stream_event_type(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def stream_event_type(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, "StreamEventType", [], opts)
  end

  @doc """
  Derive a FunctionTool from *fn*. Pure; returns a plain FunctionTool.

  `name`/`description` override derivation (name falls back to
  `fn.__name__`, description to the docstring summary paragraph, else
  None). A parameter is required iff it has no default; `Optional[X]`
  affects only value nullability (`anyOf` with null), never
  required-ness. See the module docstring for the full mapping table and
  :class:`ToolConfig` for the knobs.

  Deliberately not a decorator: a decorator would replace or wrap the
  function — magic. Call `tool(fn)` and keep *fn* yourself; dispatch with
  `{f.__name__: f for f in (...)}`.

  ## Parameters

  - `py_fn` (term())
  - `name` (String.t() | nil keyword-only default: None)
  - `description` (String.t() | nil keyword-only default: None)
  - `config` (term() keyword-only default: ToolConfig(docstring_style='auto', include_defaults=True, additional_properties_false=False, overrides=()))

  ## Returns

  - `term()`
  """
  @spec tool(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def tool(py_fn, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :tool, [py_fn], opts)
  end

  @doc """
  Create a tool result part.

  content can be a sequence of parts, a single part, or a string
  (which becomes a TextPart).  Raw bytes should be wrapped in a media part;
  use BinaryPart for arbitrary bytes that are not image/audio/video/document.

  ## Parameters

  - `id` (String.t())
  - `content` (((((((((String.t() | term()) | term()) | term()) | term()) | term()) | term()) | term()) | term())
  | term())
  - `name` (String.t() | nil keyword-only default: None)
  - `is_error` (boolean() keyword-only default: False)
  - `continuation` ((term() | term()) | nil keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec tool_result(
          String.t(),
          ((((((((String.t() | term()) | term()) | term()) | term()) | term()) | term()) | term())
           | term())
          | term(),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def tool_result(id, content, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :tool_result, [id, content], opts)
  end

  @doc """
  Forget a registered provider. Unknown ids are ignored. LMs that

  already bound it keep it.

  ## Parameters

  - `provider` (String.t())

  ## Returns

  - `nil`
  """
  @spec unregister_provider(String.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def unregister_provider(provider, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :unregister_provider, [provider], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

    iex> from dspy.lm15 import Message, Request
    iex> request = Request(model="example", messages=(Message.user("Hello"),))
    iex> request.model
    'example'

  ## Parameters

  - `instruction` (String.t())

  ## Returns

  - `%{
  optional(String.t()) =>
    (((((nil | boolean()) | integer()) | float()) | String.t())
     | list(
         (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
         | %{optional(String.t()) => term()}
       ))
    | %{
        optional(String.t()) =>
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()}
      }
  }`
  """
  @spec yes_no(String.t(), keyword()) ::
          {:ok,
           %{
             optional(String.t()) =>
               (((((nil | boolean()) | integer()) | float()) | String.t())
                | list(
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                  ))
               | %{
                   optional(String.t()) =>
                     (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                     | %{optional(String.t()) => term()}
                 }
           }}
          | {:error, Snakepit.Error.t()}
  def yes_no(instruction, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :yes_no, [instruction], opts)
  end
end
