# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: AsyncOpenAILM

defmodule Dspy.Lm15.AsyncOpenAILM do
  @moduledoc """
  AsyncOpenAILM(api_key: 'Credential | None' = None, transport: 'AsyncTransport' = <factory>, base_url: 'str' = 'https://api.openai.com/v1', profile: 'Any | None' = None, access: 'ProviderManifest | None' = None, credentials_path: "'str | os.PathLike[str] | None'" = None, account_id: 'str | None' = None, *, compat: 'Any | None' = None, settings: "'Mapping[str, str] | None'" = None, credential: 'str | None' = None, clock: "'Callable[[], datetime] | None'" = None, adaptations: 'AdaptationPolicy' = 'note')
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "AsyncOpenAILM"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `api_key` (((((String.t() | term()) | term()) | term()) | term()) | nil default: None)
  - `transport` (term() default: <factory>)
  - `base_url` (String.t() default: 'https://api.openai.com/v1')
  - `profile` (term() | nil default: None)
  - `access` (term() | nil default: None)
  - `credentials_path` ((String.t() | term()) | nil default: None)
  - `account_id` (String.t() | nil default: None)
  - `compat` (term() | nil keyword-only default: None)
  - `settings` (term() | nil keyword-only default: None)
  - `credential` (String.t() | nil keyword-only default: None)
  - `clock` (term() | nil keyword-only default: None)
  - `adaptations` (term() keyword-only default: 'note')
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec image_generate(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def image_generate(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :image_generate, [request], opts)
  end

  @doc """
  Third execution mode, async twin: returns an AsyncBatchJob.

  ## Parameters

  - `requests` (term())
  - `model` (String.t() | nil keyword-only default: None)
  - `label` (String.t() | nil keyword-only default: None)
  - `extensions` (term() keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec batch(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch(ref, requests, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :batch, [requests], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec complete(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def complete(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :complete, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `cache_id` (String.t())
  - `ttl_seconds` (integer() keyword-only, required)

  ## Returns

  - `term()`
  """
  @spec cache_update(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache_update(ref, cache_id, opts \\ []) do
    kw_keys = opts |> Keyword.keys() |> Enum.map(&to_string/1)
    missing_kw = ["ttl_seconds"] |> Enum.reject(&(&1 in kw_keys))

    if missing_kw != [] do
      raise ArgumentError,
            "Missing required keyword-only arguments: " <> Enum.join(missing_kw, ", ")
    end

    SnakeBridge.Runtime.call_method(ref, :cache_update, [cache_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `status` (integer())
  - `body` (String.t())

  ## Returns

  - `term()`
  """
  @spec normalize_error(SnakeBridge.Ref.t(), integer(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def normalize_error(ref, status, body, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :normalize_error, [status, body], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `limit` (integer() default: 20)
  - `cursor` (String.t() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec file_list(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def file_list(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :file_list, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `prefix` (term())
  - `ttl_seconds` (integer() | nil keyword-only default: None)
  - `label` (String.t() | nil keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec cache_create(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache_create(ref, prefix, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :cache_create, [prefix], opts)
  end

  @doc """
  What a call WOULD adapt (MAP-13), no network, no credential; pure, so sync.

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec plan(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def plan(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :plan, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `batch_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec batch_cancel(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_cancel(ref, batch_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :batch_cancel, [batch_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `limit` (integer() default: 20)
  - `model` (String.t() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec video_jobs(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_jobs(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :video_jobs, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `batch_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec batch_job(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_job(ref, batch_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :batch_job, [batch_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `file_id` (String.t())
  - `poll_every` (float() default: 2.0)
  - `timeout` (float() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec file_wait_ready(SnakeBridge.Ref.t(), String.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def file_wait_ready(ref, file_id, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :file_wait_ready, [file_id] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `file_id` (String.t())

  ## Returns

  - `nil`
  """
  @spec file_delete(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def file_delete(ref, file_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :file_delete, [file_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `nil`
  """
  @spec aclose(SnakeBridge.Ref.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def aclose(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :aclose, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `boolean()`
  """
  @spec has_stored_credential(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def has_stored_credential(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :has_stored_credential, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `video_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec video_result(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_result(ref, video_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :video_result, [video_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec video_submit(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_submit(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :video_submit, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `limit` (integer() default: 20)

  ## Returns

  - `term()`
  """
  @spec batches(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batches(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :batches, [] ++ List.wrap(args), opts)
  end

  @doc """
  Async mirror of BaseProviderLM.list_models (canonical ModelInfo).

  ## Returns

  - `term()`
  """
  @spec list_models(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def list_models(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :list_models, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec speech_generate(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def speech_generate(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :speech_generate, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `batch_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec batch_results(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_results(ref, batch_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :batch_results, [batch_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `limit` (integer() default: 20)
  - `model` (String.t() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec video_list(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_list(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :video_list, [] ++ List.wrap(args), opts)
  end

  @doc """
  Copy what the inner adapter's access binding resolved: the

  provider string, the credential (a per-request provider for stored
  logins, repr-suppressed), and the base URL the policy chose.

  ## Returns

  - `nil`
  """
  @spec _mirror_binding(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _mirror_binding(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_mirror_binding, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `batch_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec batch_status(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_status(ref, batch_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :batch_status, [batch_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `config` (term())

  ## Returns

  - `term()`
  """
  @spec live(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def live(ref, config, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :live, [config], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec file_upload(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def file_upload(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :file_upload, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `cache_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec cache_get(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache_get(ref, cache_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :cache_get, [cache_id], opts)
  end

  @doc """
  Run one of the inner adapter's request builders.

  A builder invokes the credential provider (AUTH-2) inside `_emit`.
  A cloud-chain provider may refresh over the network, synchronously;
  run it in a worker thread so that refresh does not block the event
  loop (D16, 2026-09-06).  A static credential needs no thread.

  ## Parameters

  - `build` (term())
  - `args` (term())
  - `kwargs` (term())

  ## Returns

  - `term()`
  """
  @spec _build(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _build(ref, build, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :_build, [build] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec _astream(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _astream(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_astream, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `file_id` (String.t())

  ## Returns

  - `binary()`
  """
  @spec file_download(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, binary()} | {:error, Snakepit.Error.t()}
  def file_download(ref, file_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :file_download, [file_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `file_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec file_get(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def file_get(ref, file_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :file_get, [file_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `limit` (integer() default: 20)

  ## Returns

  - `term()`
  """
  @spec batch_list(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_list(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :batch_list, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec batch_submit(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def batch_submit(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :batch_submit, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `limit` (integer() default: 20)
  - `cursor` (String.t() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec cache_list(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache_list(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :cache_list, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())
  - `req` (term() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec _stream_raw(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _stream_raw(ref, request, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :_stream_raw, [request] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `video_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec video_job(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_job(ref, video_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :video_job, [video_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `cache_id` (String.t())

  ## Returns

  - `nil`
  """
  @spec cache_delete(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def cache_delete(ref, cache_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :cache_delete, [cache_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `endpoint` (String.t())

  ## Returns

  - `term()`
  """
  @spec _async_unsupported(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _async_unsupported(ref, endpoint, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_async_unsupported, [endpoint], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec stream(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def stream(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :stream, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec _send(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _send(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_send, [request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `video_id` (String.t())

  ## Returns

  - `term()`
  """
  @spec video_status(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_status(ref, video_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :video_status, [video_id], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `prefix` (term())
  - `ttl_seconds` (integer() | nil keyword-only default: None)
  - `label` (String.t() | nil keyword-only default: None)

  ## Returns

  - `term()`
  """
  @spec cache(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache(ref, prefix, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :cache, [prefix], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec video_generate(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def video_generate(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :video_generate, [request], opts)
  end

  @spec _inner(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _inner(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_inner)
  end

  @spec access(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def access(ref) do
    SnakeBridge.Runtime.get_attr(ref, :access)
  end

  @spec account_id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def account_id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :account_id)
  end

  @spec adaptations(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def adaptations(ref) do
    SnakeBridge.Runtime.get_attr(ref, :adaptations)
  end

  @spec api_key(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def api_key(ref) do
    SnakeBridge.Runtime.get_attr(ref, :api_key)
  end

  @spec base_url(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def base_url(ref) do
    SnakeBridge.Runtime.get_attr(ref, :base_url)
  end

  @spec clock(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def clock(ref) do
    SnakeBridge.Runtime.get_attr(ref, :clock)
  end

  @spec compat(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def compat(ref) do
    SnakeBridge.Runtime.get_attr(ref, :compat)
  end

  @spec credential(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def credential(ref) do
    SnakeBridge.Runtime.get_attr(ref, :credential)
  end

  @spec credentials_path(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def credentials_path(ref) do
    SnakeBridge.Runtime.get_attr(ref, :credentials_path)
  end

  @spec manifest(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def manifest(ref) do
    SnakeBridge.Runtime.get_attr(ref, :manifest)
  end

  @spec profile(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def profile(ref) do
    SnakeBridge.Runtime.get_attr(ref, :profile)
  end

  @spec provider(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider)
  end

  @spec settings(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def settings(ref) do
    SnakeBridge.Runtime.get_attr(ref, :settings)
  end

  @spec supports(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def supports(ref) do
    SnakeBridge.Runtime.get_attr(ref, :supports)
  end

  @spec transport(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def transport(ref) do
    SnakeBridge.Runtime.get_attr(ref, :transport)
  end
end
