# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: AsyncVideoJob

defmodule Dspy.Lm15.AsyncVideoJob do
  @moduledoc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "AsyncVideoJob"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `lm` (term())
  - `info` (term())
  """
  @spec new(term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(lm, info, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [lm, info], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec refresh(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def refresh(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :refresh, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec result(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def result(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :result, [], opts)
  end

  @doc """
  Native cancellable wait. Neither cancellation nor timeout cancels the job.

  ## Parameters

  - `poll_every` (float() default: 5.0)
  - `timeout` (float() | nil default: 300.0)

  ## Returns

  - `term()`
  """
  @spec wait(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec wait(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec wait(SnakeBridge.Ref.t(), float()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec wait(SnakeBridge.Ref.t(), float(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec wait(SnakeBridge.Ref.t(), float(), float() | nil) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec wait(SnakeBridge.Ref.t(), float(), float() | nil, keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def wait(ref) do
    SnakeBridge.Runtime.call_method(ref, :wait, [], [])
  end

  def wait(ref, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_method(ref, :wait, [], opts)
  end

  def wait(ref, poll_every) do
    SnakeBridge.Runtime.call_method(ref, :wait, [poll_every], [])
  end

  def wait(ref, poll_every, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_method(ref, :wait, [poll_every], opts)
  end

  def wait(ref, poll_every, timeout) do
    SnakeBridge.Runtime.call_method(ref, :wait, [poll_every, timeout], [])
  end

  def wait(ref, poll_every, timeout, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_method(ref, :wait, [poll_every, timeout], opts)
  end

  @spec id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :id)
  end

  @spec info(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def info(ref) do
    SnakeBridge.Runtime.get_attr(ref, :info)
  end

  @spec progress(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def progress(ref) do
    SnakeBridge.Runtime.get_attr(ref, :progress)
  end

  @spec status(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def status(ref) do
    SnakeBridge.Runtime.get_attr(ref, :status)
  end
end
