# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: AsyncResponseStream

defmodule Dspy.Lm15.AsyncResponseStream do
  @moduledoc """
  Async mirror of :class:`ResponseStream`, same accumulator engine.

  rs = AsyncResponseStream(lm.stream(request), request)
      async for text in rs:
          print(text, end="")
      response = await rs.response()

  `response()` is a method (it may need to consume the stream, which
  is an awaitable operation in async code).
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "AsyncResponseStream"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `events` (term())
  - `request` (term())
  """
  @spec new(term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(events, request, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [events, request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `primary` (term() | nil default: None)

  ## Returns

  - `nil`
  """
  @spec _close_source(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _close_source(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :_close_source, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec _pump(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _pump(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_pump, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `exc` (term())

  ## Returns

  - `nil`
  """
  @spec _record_cleanup(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _record_cleanup(ref, exc, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_record_cleanup, [exc], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec _text_iter(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _text_iter(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_text_iter, [], opts)
  end

  @doc """
  Stop reading and release the source, without draining it.

  ## Returns

  - `nil`
  """
  @spec aclose(SnakeBridge.Ref.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def aclose(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :aclose, [], opts)
  end

  @doc """
  Canonical stream events, teed through the accumulator.

  ## Returns

  - `term()`
  """
  @spec events(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def events(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :events, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec response(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def response(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :response, [], opts)
  end
end
