# Generated by SnakeBridge v0.18.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: AudioFormat

defmodule Dspy.Lm15.AudioFormat do
  @moduledoc """
  AudioFormat(encoding: 'AudioEncoding', sample_rate: 'int', channels: 'int' = 1)
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "AudioFormat"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `encoding` (term())
  - `sample_rate` (integer())
  - `channels` (integer() default: 1)
  """
  @spec new(term(), integer()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), integer(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), integer(), integer()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), integer(), integer(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(encoding, sample_rate) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [encoding, sample_rate], [])
  end

  def new(encoding, sample_rate, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [encoding, sample_rate], opts)
  end

  def new(encoding, sample_rate, channels) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [encoding, sample_rate, channels], [])
  end

  def new(encoding, sample_rate, channels, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [encoding, sample_rate, channels], opts)
  end

  @spec channels(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def channels(ref) do
    SnakeBridge.Runtime.get_attr(ref, :channels)
  end

  @spec encoding(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def encoding(ref) do
    SnakeBridge.Runtime.get_attr(ref, :encoding)
  end

  @spec sample_rate(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def sample_rate(ref) do
    SnakeBridge.Runtime.get_attr(ref, :sample_rate)
  end
end
