# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: BatchRequest

defmodule Dspy.Lm15.BatchRequest do
  @moduledoc """
  A batch of model requests.

  Each nested Request carries its own model.  The optional top-level model is
  only a routing/default convenience; when omitted, it is inferred from the
  first nested request and does not constrain the rest of the batch.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "BatchRequest"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `model` (String.t() | nil default: None)
  - `requests` ({term(), term()} default: ())
  - `label` (String.t() | nil default: None)
  - `extensions` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  }
  | nil default: None)
  """
  @spec new() :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, {term(), term()}) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, {term(), term()}, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, {term(), term()}, String.t() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, {term(), term()}, String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t() | nil,
          {term(), term()},
          String.t() | nil,
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          }
          | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t() | nil,
          {term(), term()},
          String.t() | nil,
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          }
          | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new() do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], [])
  end

  def new(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  def new(model) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model], [])
  end

  def new(model, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model], opts)
  end

  def new(model, requests) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, requests], [])
  end

  def new(model, requests, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, requests], opts)
  end

  def new(model, requests, label) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, requests, label], [])
  end

  def new(model, requests, label, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, requests, label], opts)
  end

  def new(model, requests, label, extensions) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [model, requests, label, extensions],
      []
    )
  end

  def new(model, requests, label, extensions, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [model, requests, label, extensions],
      opts
    )
  end

  @spec extensions(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def extensions(ref) do
    SnakeBridge.Runtime.get_attr(ref, :extensions)
  end

  @spec label(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def label(ref) do
    SnakeBridge.Runtime.get_attr(ref, :label)
  end

  @spec model(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model)
  end

  @spec requests(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def requests(ref) do
    SnakeBridge.Runtime.get_attr(ref, :requests)
  end
end
