# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: BuiltinTool

defmodule Dspy.Lm15.BuiltinTool do
  @moduledoc """
  A provider-native tool (web search, code execution, etc.).
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "BuiltinTool"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `name` (String.t())
  - `config` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  }
  | nil default: None)
  """
  @spec new(String.t()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          }
          | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          }
          | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(name) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [name], [])
  end

  def new(name, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [name], opts)
  end

  def new(name, config) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [name, config], [])
  end

  def new(name, config, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [name, config], opts)
  end

  @spec config(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def config(ref) do
    SnakeBridge.Runtime.get_attr(ref, :config)
  end

  @spec name(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def name(ref) do
    SnakeBridge.Runtime.get_attr(ref, :name)
  end

  @spec type(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def type(ref) do
    SnakeBridge.Runtime.get_attr(ref, :type)
  end
end
