# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: CachePage

defmodule Dspy.Lm15.CachePage do
  @moduledoc """
  One page of stored cache objects plus an opaque continuation cursor.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "CachePage"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `items` ({term(), term()} default: ())
  - `next_cursor` (String.t() | nil default: None)
  """
  @spec new() :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new({term(), term()}) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new({term(), term()}, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new({term(), term()}, String.t() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new({term(), term()}, String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new() do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], [])
  end

  def new(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  def new(items) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [items], [])
  end

  def new(items, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [items], opts)
  end

  def new(items, next_cursor) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [items, next_cursor], [])
  end

  def new(items, next_cursor, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [items, next_cursor], opts)
  end

  @spec items(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def items(ref) do
    SnakeBridge.Runtime.get_attr(ref, :items)
  end

  @spec next_cursor(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def next_cursor(ref) do
    SnakeBridge.Runtime.get_attr(ref, :next_cursor)
  end
end
