# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: CitationDelta

defmodule Dspy.Lm15.CitationDelta do
  @moduledoc """
  A citation fragment arriving during streaming.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "CitationDelta"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `text` (String.t() | nil default: None)
  - `url` (String.t() | nil default: None)
  - `title` (String.t() | nil default: None)
  - `part_index` (integer() default: 0)
  """
  @spec new() :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, String.t() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, String.t() | nil, String.t() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, String.t() | nil, String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, String.t() | nil, String.t() | nil, integer()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t() | nil, String.t() | nil, String.t() | nil, integer(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new() do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], [])
  end

  def new(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  def new(text) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text], [])
  end

  def new(text, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text], opts)
  end

  def new(text, url) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, url], [])
  end

  def new(text, url, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, url], opts)
  end

  def new(text, url, title) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, url, title], [])
  end

  def new(text, url, title, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, url, title], opts)
  end

  def new(text, url, title, part_index) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, url, title, part_index], [])
  end

  def new(text, url, title, part_index, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, url, title, part_index], opts)
  end

  @spec part_index(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def part_index(ref) do
    SnakeBridge.Runtime.get_attr(ref, :part_index)
  end

  @spec text(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def text(ref) do
    SnakeBridge.Runtime.get_attr(ref, :text)
  end

  @spec title(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def title(ref) do
    SnakeBridge.Runtime.get_attr(ref, :title)
  end

  @spec type(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def type(ref) do
    SnakeBridge.Runtime.get_attr(ref, :type)
  end

  @spec url(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def url(ref) do
    SnakeBridge.Runtime.get_attr(ref, :url)
  end
end
