# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: CollectionLimitError

defmodule Dspy.Lm15.CollectionLimitError do
  @moduledoc """
  A local turn collector reached its budget, not a provider failure.

  Non-retryable. `partial_events` preserves the accepted events without
  copying their payloads. `partial` materializes them on demand as an
  incomplete Turn. A byte-limit failure also exposes `rejected_event`:
  it was received but not yielded or added to the collection. Process it
  before resuming raw session reads if that content is needed.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "CollectionLimitError"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `message` (String.t() default: '')
  - `limit` (String.t() | nil keyword-only default: None)
  - `maximum` (integer() | nil keyword-only default: None)
  - `retained_bytes` (integer() keyword-only default: 0)
  - `partial_events` (tuple() keyword-only default: ())
  - `rejected_event` (term() keyword-only default: None)
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Add a note to the exception

  ## Parameters

  - `note` (term())

  ## Returns

  - `term()`
  """
  @spec add_note(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def add_note(ref, note, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :add_note, [note], opts)
  end

  @doc """
  Set self.__traceback__ to tb and return self.

  ## Parameters

  - `tb` (term())

  ## Returns

  - `term()`
  """
  @spec with_traceback(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def with_traceback(ref, tb, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :with_traceback, [tb], opts)
  end

  @spec args(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def args(ref) do
    SnakeBridge.Runtime.get_attr(ref, :args)
  end

  @spec default_code(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def default_code(ref) do
    SnakeBridge.Runtime.get_attr(ref, :default_code)
  end

  @spec partial(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def partial(ref) do
    SnakeBridge.Runtime.get_attr(ref, :partial)
  end
end
