# Generated by SnakeBridge v0.18.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ContinuationDelta

defmodule Dspy.Lm15.ContinuationDelta do
  @moduledoc """
  Opaque provider continuation state arriving during streaming.

  part_index=None attaches the state to the assistant message; otherwise it
  attaches to the completed part with that index.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ContinuationDelta"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `provider` (String.t())
  - `kind` (String.t())
  - `data` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  } default: <factory>)
  - `part_index` (integer() | nil default: None)
  """
  @spec new(String.t(), String.t()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t())
             | list(
                 (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                 | %{optional(String.t()) => term()}
               ))
            | %{
                optional(String.t()) =>
                  (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                  | %{optional(String.t()) => term()}
              }
        }) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          String.t(),
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          },
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          String.t(),
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          },
          integer() | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          String.t(),
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          },
          integer() | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(provider, kind) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [provider, kind], [])
  end

  def new(provider, kind, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [provider, kind], opts)
  end

  def new(provider, kind, data) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [provider, kind, data], [])
  end

  def new(provider, kind, data, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [provider, kind, data], opts)
  end

  def new(provider, kind, data, part_index) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [provider, kind, data, part_index], [])
  end

  def new(provider, kind, data, part_index, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [provider, kind, data, part_index],
      opts
    )
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec to_state(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def to_state(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :to_state, [], opts)
  end

  @spec data(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def data(ref) do
    SnakeBridge.Runtime.get_attr(ref, :data)
  end

  @spec kind(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def kind(ref) do
    SnakeBridge.Runtime.get_attr(ref, :kind)
  end

  @spec part_index(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def part_index(ref) do
    SnakeBridge.Runtime.get_attr(ref, :part_index)
  end

  @spec provider(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider)
  end

  @spec type(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def type(ref) do
    SnakeBridge.Runtime.get_attr(ref, :type)
  end
end
