# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ContinuationState

defmodule Dspy.Lm15.ContinuationState do
  @moduledoc """
  Opaque provider-owned state needed to continue/replay a transcript.

  Continuation state is not visible model content.  It travels with the
  Message or Part it describes so provider adapters can reconstruct future
  provider requests without relying on detached response metadata.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ContinuationState"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `provider` (String.t())
  - `kind` (String.t())
  - `data` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  } default: <factory>)
  """
  @spec new(String.t(), String.t(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(provider, kind, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [provider, kind] ++ List.wrap(args),
      opts
    )
  end

  @spec data(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def data(ref) do
    SnakeBridge.Runtime.get_attr(ref, :data)
  end

  @spec kind(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def kind(ref) do
    SnakeBridge.Runtime.get_attr(ref, :kind)
  end

  @spec provider(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider)
  end
end
