# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: DataPart

defmodule Dspy.Lm15.DataPart do
  @moduledoc """
  Structured data as content (changes/2026-09-17-judgments.md, D2).

  In a user/system message: structured input (a provider that reads
  JSON state takes `value` as such; a text-only wire gets it as JSON
  text).  In an assistant message: the answer to a `json_schema`
  request that declares judgments (MAP-14) — `value` is the model's
  JSON object, `probabilities` a distribution per judgment over its
  declared keys when one was measured, `method` how (JudgmentMethod).
  `value` is an opaque payload: any JSON value, verbatim (INV-002).
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "DataPart"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `value` ((((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
  | %{optional(String.t()) => term()})
  - `probabilities` (%{optional(String.t()) => %{optional(String.t()) => float()}} | nil default: None)
  - `method` (term() | nil default: None)
  - `continuation` ({term(), term()} default: ())
  """
  @spec new(
          (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
          | %{optional(String.t()) => term()},
          list(term()),
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(value, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [value] ++ List.wrap(args), opts)
  end

  @spec continuation(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def continuation(ref) do
    SnakeBridge.Runtime.get_attr(ref, :continuation)
  end

  @spec method(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def method(ref) do
    SnakeBridge.Runtime.get_attr(ref, :method)
  end

  @spec probabilities(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def probabilities(ref) do
    SnakeBridge.Runtime.get_attr(ref, :probabilities)
  end

  @spec type(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def type(ref) do
    SnakeBridge.Runtime.get_attr(ref, :type)
  end

  @spec value(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def value(ref) do
    SnakeBridge.Runtime.get_attr(ref, :value)
  end
end
