# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ErrorDetail

defmodule Dspy.Lm15.ErrorDetail do
  @moduledoc """
  Structured error information.  A dataclass, not a dict.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ErrorDetail"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `code` (term())
  - `message` (String.t())
  - `provider_code` (String.t() | nil default: None)
  - `http_response` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  } default: <factory>)
  """
  @spec new(term(), String.t()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), String.t(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), String.t(), String.t() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), String.t(), String.t() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), String.t(), String.t() | nil, %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t())
             | list(
                 (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                 | %{optional(String.t()) => term()}
               ))
            | %{
                optional(String.t()) =>
                  (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                  | %{optional(String.t()) => term()}
              }
        }) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          term(),
          String.t(),
          String.t() | nil,
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          },
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(code, message) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [code, message], [])
  end

  def new(code, message, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [code, message], opts)
  end

  def new(code, message, provider_code) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [code, message, provider_code], [])
  end

  def new(code, message, provider_code, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [code, message, provider_code], opts)
  end

  def new(code, message, provider_code, http_response) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [code, message, provider_code, http_response],
      []
    )
  end

  def new(code, message, provider_code, http_response, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [code, message, provider_code, http_response],
      opts
    )
  end

  @spec code(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def code(ref) do
    SnakeBridge.Runtime.get_attr(ref, :code)
  end

  @spec http_response(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def http_response(ref) do
    SnakeBridge.Runtime.get_attr(ref, :http_response)
  end

  @spec message(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def message(ref) do
    SnakeBridge.Runtime.get_attr(ref, :message)
  end

  @spec provider_code(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider_code(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider_code)
  end
end
