# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: FunctionTool

defmodule Dspy.Lm15.FunctionTool do
  @moduledoc """
  Serializable function tool specification sent to the model.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "FunctionTool"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `name` (String.t())
  - `description` (String.t() | nil default: None)
  - `parameters` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  } default: <factory>)
  """
  @spec new(String.t(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(name, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [name] ++ List.wrap(args), opts)
  end

  @spec description(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def description(ref) do
    SnakeBridge.Runtime.get_attr(ref, :description)
  end

  @spec name(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def name(ref) do
    SnakeBridge.Runtime.get_attr(ref, :name)
  end

  @spec parameters(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def parameters(ref) do
    SnakeBridge.Runtime.get_attr(ref, :parameters)
  end

  @spec type(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def type(ref) do
    SnakeBridge.Runtime.get_attr(ref, :type)
  end
end
