# Generated by SnakeBridge v0.18.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ModelInfo

defmodule Dspy.Lm15.ModelInfo do
  @moduledoc """
  ModelInfo(id: 'str', provider: 'str', api_family: 'str', aliases: 'tuple[str, ...]' = (), origin: 'ModelOrigin' = <factory>, inference: 'InferenceModelInfo | None' = None, compat: 'CompatProfile | None' = None, extensions: 'JsonObject | None' = None)
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ModelInfo"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `id` (term())
  - `provider` (term())
  - `api_family` (term())
  - `aliases` (term() default: ())
  - `origin` (term() default: <factory>)
  - `inference` (term() default: None)
  - `compat` (term() default: None)
  - `extensions` (term() default: None)
  """
  @spec new(term(), term(), term()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), term()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), term(), term()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), term(), term(), term()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term(), term(), term(), term(), term(), term(), term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(id, provider, api_family) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [id, provider, api_family], [])
  end

  def new(id, provider, api_family, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [id, provider, api_family], opts)
  end

  def new(id, provider, api_family, aliases) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [id, provider, api_family, aliases], [])
  end

  def new(id, provider, api_family, aliases, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases],
      opts
    )
  end

  def new(id, provider, api_family, aliases, origin) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin],
      []
    )
  end

  def new(id, provider, api_family, aliases, origin, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin],
      opts
    )
  end

  def new(id, provider, api_family, aliases, origin, inference) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin, inference],
      []
    )
  end

  def new(id, provider, api_family, aliases, origin, inference, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin, inference],
      opts
    )
  end

  def new(id, provider, api_family, aliases, origin, inference, compat) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin, inference, compat],
      []
    )
  end

  def new(id, provider, api_family, aliases, origin, inference, compat, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin, inference, compat],
      opts
    )
  end

  def new(id, provider, api_family, aliases, origin, inference, compat, extensions) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin, inference, compat, extensions],
      []
    )
  end

  def new(id, provider, api_family, aliases, origin, inference, compat, extensions, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, provider, api_family, aliases, origin, inference, compat, extensions],
      opts
    )
  end

  @spec aliases(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def aliases(ref) do
    SnakeBridge.Runtime.get_attr(ref, :aliases)
  end

  @spec api_family(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def api_family(ref) do
    SnakeBridge.Runtime.get_attr(ref, :api_family)
  end

  @spec compat(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def compat(ref) do
    SnakeBridge.Runtime.get_attr(ref, :compat)
  end

  @spec extensions(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def extensions(ref) do
    SnakeBridge.Runtime.get_attr(ref, :extensions)
  end

  @spec id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :id)
  end

  @spec inference(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def inference(ref) do
    SnakeBridge.Runtime.get_attr(ref, :inference)
  end

  @spec origin(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def origin(ref) do
    SnakeBridge.Runtime.get_attr(ref, :origin)
  end

  @spec provider(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider)
  end
end
