# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ModelSupport

defmodule Dspy.Lm15.ModelSupport do
  @moduledoc """
  What a model behind a declared provider supports, stated by the caller.

  A compat policy says what the wire accepts; whether a model honours it is
  model knowledge. None means "not stated": DSPy then reads the metadata
  snapshot through the provider's `metadata_namespaces`, and treats what
  is still unknown as unsupported (the rule built-in providers live with).
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ModelSupport"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `function_calling` (boolean() | nil default: None)
  - `reasoning` (boolean() | nil default: None)
  - `response_schema` (boolean() | nil default: None)
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  This support, with unstated fields taken from `other`.

  ## Parameters

  - `other` (Dspy.Lm15.ModelSupport.t() | nil)

  ## Returns

  - `Dspy.Lm15.ModelSupport.t()`
  """
  @spec over(SnakeBridge.Ref.t(), Dspy.Lm15.ModelSupport.t() | nil, keyword()) ::
          {:ok, Dspy.Lm15.ModelSupport.t()} | {:error, Snakepit.Error.t()}
  def over(ref, other, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :over, [other], opts)
  end

  @spec function_calling(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def function_calling(ref) do
    SnakeBridge.Runtime.get_attr(ref, :function_calling)
  end

  @spec reasoning(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def reasoning(ref) do
    SnakeBridge.Runtime.get_attr(ref, :reasoning)
  end

  @spec response_schema(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def response_schema(ref) do
    SnakeBridge.Runtime.get_attr(ref, :response_schema)
  end
end
