# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ModelRegistry

defmodule Dspy.Lm15.ModelRegistry do
  @moduledoc """
  ModelRegistry(_models: 'dict[tuple[str, str], ModelInfo]' = <factory>, _aliases: 'dict[tuple[str, str], tuple[str, str]]' = <factory>)
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ModelRegistry"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `models` (%{optional({String.t(), String.t()}) => term()} default: <factory>)
  - `aliases` (%{optional({String.t(), String.t()}) => {String.t(), String.t()}} default: <factory>)
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `model` (term())
  - `replace` (boolean() keyword-only default: True)

  ## Returns

  - `nil`
  """
  @spec add(SnakeBridge.Ref.t(), term(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def add(ref, model, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :add, [model], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `profile` (term())
  - `replace` (boolean() keyword-only default: True)

  ## Returns

  - `nil`
  """
  @spec add_profile(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def add_profile(ref, profile, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :add_profile, [profile], opts)
  end

  @doc """
  Hydrate a registry from installed entry-point catalogs.

  Each entry point in `group` must load to a zero-argument callable
  returning an iterable of canonical ModelInfo dicts
  (docs/model-hydration.md). Catalogs are processed sorted by
  entry-point name; on duplicate (provider, id) keys the FIRST
  occurrence wins. A catalog that raises is skipped with a warning —
  discovery never crashes the host application.

  Hydrated data is ADVISORY metadata only: it must never change what
  build_request produces.

  ## Parameters

  - `group` (String.t() keyword-only default: 'lm15.model_catalogs')

  ## Returns

  - `term()`
  """
  @spec discover(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def discover(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :discover, [], opts)
  end

  @doc """
  Build a registry from canonical ModelInfo dicts.

  Each dict is validated through `serde.model_info_from_dict`; the
  ModelInfo constructors reject junk (negative prices, empty modality
  names, missing id/provider) by raising ValueError/TypeError.

  ## Parameters

  - `dicts` (term())

  ## Returns

  - `term()`
  """
  @spec from_dicts(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def from_dicts(ref, dicts, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :from_dicts, [dicts], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `profiles` (term())

  ## Returns

  - `term()`
  """
  @spec from_profiles(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def from_profiles(ref, profiles, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :from_profiles, [profiles], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `provider` (String.t())
  - `model` (String.t())

  ## Returns

  - `term() | nil`
  """
  @spec get(SnakeBridge.Ref.t(), String.t(), String.t(), keyword()) ::
          {:ok, term() | nil} | {:error, Snakepit.Error.t()}
  def get(ref, provider, model, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get, [provider, model], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `provider` (String.t() | nil default: None)

  ## Returns

  - `{term(), term()}`
  """
  @spec list(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, {term(), term()}} | {:error, Snakepit.Error.t()}
  def list(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :list, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `{String.t(), term()}`
  """
  @spec providers(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, {String.t(), term()}} | {:error, Snakepit.Error.t()}
  def providers(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :providers, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `model` (String.t())
  - `provider` (String.t() | nil default: None)

  ## Returns

  - `term() | nil`
  """
  @spec resolve(SnakeBridge.Ref.t(), String.t(), list(term()), keyword()) ::
          {:ok, term() | nil} | {:error, Snakepit.Error.t()}
  def resolve(ref, model, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :resolve, [model] ++ List.wrap(args), opts)
  end

  @spec _aliases(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _aliases(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_aliases)
  end

  @spec _models(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _models(ref) do
    SnakeBridge.Runtime.get_attr(ref, :_models)
  end
end
