# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: Resolution

defmodule Dspy.Lm15.Resolution do
  @moduledoc """
  The complete answer to "how did you route this string".

  `resolve()` returning this IS the explain() method — there is no
  separate one.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "Resolution"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `requested` (String.t())
  - `model` (String.t())
  - `provider` (String.t())
  - `adapter` (String.t())
  - `source` (String.t())
  - `rule` (term() | nil default: None)
  - `env_key` (String.t() | nil default: None)
  - `model_info` (term() | nil default: None)
  - `compat` ((((String.t() | term()) | term()) | term()) | nil default: None)
  - `declared` (boolean() default: False)
  - `credential_policy` (String.t() default: 'key')
  - `placeholder_key` (String.t() | nil default: None)
  """
  @spec new(String.t(), String.t(), String.t(), String.t(), String.t(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(requested, model, provider, adapter, source, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [requested, model, provider, adapter, source] ++ List.wrap(args),
      opts
    )
  end

  @doc """
  One-paragraph human-readable explanation of this resolution.

  ## Returns

  - `String.t()`
  """
  @spec describe(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def describe(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :describe, [], opts)
  end

  @spec adapter(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def adapter(ref) do
    SnakeBridge.Runtime.get_attr(ref, :adapter)
  end

  @spec compat(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def compat(ref) do
    SnakeBridge.Runtime.get_attr(ref, :compat)
  end

  @spec credential_policy(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def credential_policy(ref) do
    SnakeBridge.Runtime.get_attr(ref, :credential_policy)
  end

  @spec declared(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def declared(ref) do
    SnakeBridge.Runtime.get_attr(ref, :declared)
  end

  @spec env_key(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def env_key(ref) do
    SnakeBridge.Runtime.get_attr(ref, :env_key)
  end

  @spec model(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model)
  end

  @spec model_info(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model_info(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model_info)
  end

  @spec placeholder_key(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def placeholder_key(ref) do
    SnakeBridge.Runtime.get_attr(ref, :placeholder_key)
  end

  @spec provider(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider)
  end

  @spec requested(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def requested(ref) do
    SnakeBridge.Runtime.get_attr(ref, :requested)
  end

  @spec rule(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def rule(ref) do
    SnakeBridge.Runtime.get_attr(ref, :rule)
  end

  @spec source(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def source(ref) do
    SnakeBridge.Runtime.get_attr(ref, :source)
  end
end
