# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: Response

defmodule Dspy.Lm15.Response do
  @moduledoc """
  The composed artifact returned by a foundation model.

  `Response` keeps only minimal convenience properties.  Use
  `response.message.first(...)` and `response.message.parts_of(...)`
  for variant-specific content access.

  `logprobs_complete=False` means local text editing could not preserve
  scores for all retained text. Remaining scores describe whole original
  tokens only; never infer a probability for the unscored text. True is
  the default and does not promise the provider supplied scores at all.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "Response"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `id` (String.t() | nil)
  - `model` (String.t())
  - `message` (term())
  - `finish_reason` (term())
  - `usage` (term())
  - `logprobs` ({term(), term()} | nil default: None)
  - `provider_data` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  }
  | nil default: None)
  - `adaptations` ({term(), term()} default: ())
  - `logprobs_complete` (boolean() keyword-only default: True)
  """
  @spec new(String.t() | nil, String.t(), term(), term(), term(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(id, model, message, finish_reason, usage, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [id, model, message, finish_reason, usage] ++ List.wrap(args),
      opts
    )
  end

  @doc """
  Σ p·i over an ordered judgment's levels (Jev's `score`), or None.

  ## Parameters

  - `field_name` (String.t())

  ## Returns

  - `float() | nil`
  """
  @spec expected(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, float() | nil} | {:error, Snakepit.Error.t()}
  def expected(ref, field_name, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :expected, [field_name], opts)
  end

  @doc """
  Parse the response text as exact JSON.

  ## Parameters

  - `default` (term())

  ## Returns

  - `term()`
  """
  @spec parse_json(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def parse_json(ref, default, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :parse_json, [default], opts)
  end

  @spec adaptations(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def adaptations(ref) do
    SnakeBridge.Runtime.get_attr(ref, :adaptations)
  end

  @spec citations(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def citations(ref) do
    SnakeBridge.Runtime.get_attr(ref, :citations)
  end

  @spec data(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def data(ref) do
    SnakeBridge.Runtime.get_attr(ref, :data)
  end

  @spec finish_reason(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def finish_reason(ref) do
    SnakeBridge.Runtime.get_attr(ref, :finish_reason)
  end

  @spec id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :id)
  end

  @spec json(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def json(ref) do
    SnakeBridge.Runtime.get_attr(ref, :json)
  end

  @spec logprobs(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logprobs(ref) do
    SnakeBridge.Runtime.get_attr(ref, :logprobs)
  end

  @spec logprobs_complete(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logprobs_complete(ref) do
    SnakeBridge.Runtime.get_attr(ref, :logprobs_complete)
  end

  @spec message(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def message(ref) do
    SnakeBridge.Runtime.get_attr(ref, :message)
  end

  @spec method(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def method(ref) do
    SnakeBridge.Runtime.get_attr(ref, :method)
  end

  @spec model(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model)
  end

  @spec probabilities(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def probabilities(ref) do
    SnakeBridge.Runtime.get_attr(ref, :probabilities)
  end

  @spec provider_data(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider_data(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider_data)
  end

  @spec text(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def text(ref) do
    SnakeBridge.Runtime.get_attr(ref, :text)
  end

  @spec tool_calls(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def tool_calls(ref) do
    SnakeBridge.Runtime.get_attr(ref, :tool_calls)
  end

  @spec usage(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def usage(ref) do
    SnakeBridge.Runtime.get_attr(ref, :usage)
  end
end
