# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: ResponseStream

defmodule Dspy.Lm15.ResponseStream do
  @moduledoc """
  Lazy stream-backed response assembler.

  rs = ResponseStream(lm.stream(request), request)
      for text in rs:              # text as it arrives
          print(text, end="")
      rs.response                  # the same Response complete() returns

  `rs.events()` yields the canonical StreamEvents instead — one
  vocabulary for raw and assembled streaming.  Accessors mirror
  Response's own minimal set; everything richer is
  `rs.response.message.first(...)` / `.parts_of(...)`.

  Tool calls are surfaced as data only; ResponseStream never executes
  anything.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "ResponseStream"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `events` (term())
  - `request` (term())
  """
  @spec new(term(), term(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(events, request, opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [events, request], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `primary` (term() | nil default: None)

  ## Returns

  - `nil`
  """
  @spec _close_source(SnakeBridge.Ref.t(), list(term()), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _close_source(ref, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :_close_source, [] ++ List.wrap(args), opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Returns

  - `term()`
  """
  @spec _pump(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def _pump(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_pump, [], opts)
  end

  @doc """
  Use the lm15 types and providers bundled with DSPy.

  Import public names here rather than from DSPy's private vendor directory.
  These are the original lm15 objects, not copies or subclasses. `dspy.LM`
  accepts explicit Request objects and uses them in its native engine path.

  ## Examples

      iex> from dspy.lm15 import Message, Request
      iex> request = Request(model="example", messages=(Message.user("Hello"),))
      iex> request.model
      'example'

  ## Parameters

  - `exc` (term())

  ## Returns

  - `nil`
  """
  @spec _record_cleanup(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _record_cleanup(ref, exc, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_record_cleanup, [exc], opts)
  end

  @doc """
  Stop reading and release the source, without draining it.

  An unfinished stream has no complete response. Closing does not
  promise that the provider stops generating or billing immediately.

  ## Returns

  - `nil`
  """
  @spec close(SnakeBridge.Ref.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def close(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :close, [], opts)
  end

  @doc """
  Canonical stream events, teed through the accumulator.

  ## Returns

  - `term()`
  """
  @spec events(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def events(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :events, [], opts)
  end

  @spec citations(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def citations(ref) do
    SnakeBridge.Runtime.get_attr(ref, :citations)
  end

  @spec finish_reason(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def finish_reason(ref) do
    SnakeBridge.Runtime.get_attr(ref, :finish_reason)
  end

  @spec json(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def json(ref) do
    SnakeBridge.Runtime.get_attr(ref, :json)
  end

  @spec model(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model)
  end

  @spec response(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def response(ref) do
    SnakeBridge.Runtime.get_attr(ref, :response)
  end

  @spec text(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def text(ref) do
    SnakeBridge.Runtime.get_attr(ref, :text)
  end

  @spec tool_calls(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def tool_calls(ref) do
    SnakeBridge.Runtime.get_attr(ref, :tool_calls)
  end

  @spec usage(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def usage(ref) do
    SnakeBridge.Runtime.get_attr(ref, :usage)
  end
end
