# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: SpeechGenerationResponse

defmodule Dspy.Lm15.SpeechGenerationResponse do
  @moduledoc """
  SpeechGenerationResponse(audio: 'AudioPart', id: 'str | None' = None, model: 'str | None' = None, usage: 'Usage' = <factory>, provider_data: 'ProviderData | None' = None)
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "SpeechGenerationResponse"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `audio` (term())
  - `id` (String.t() | nil default: None)
  - `model` (String.t() | nil default: None)
  - `usage` (term() default: <factory>)
  - `provider_data` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  }
  | nil default: None)
  """
  @spec new(term(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(audio, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [audio] ++ List.wrap(args), opts)
  end

  @spec audio(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def audio(ref) do
    SnakeBridge.Runtime.get_attr(ref, :audio)
  end

  @spec id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :id)
  end

  @spec model(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model)
  end

  @spec provider_data(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def provider_data(ref) do
    SnakeBridge.Runtime.get_attr(ref, :provider_data)
  end

  @spec usage(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def usage(ref) do
    SnakeBridge.Runtime.get_attr(ref, :usage)
  end
end
