# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: StreamCleanupWarning

defmodule Dspy.Lm15.StreamCleanupWarning do
  @moduledoc """
  A stream's source failed after the Response was already complete.

  Emitted (`warnings.warn`) when, after the end event has been yielded,
  the source raises while draining or its `close()`/`aclose()` raises.
  The provider finished the turn and billed it; the Response is returned
  unchanged.  The failure is about the connection's afterlife, not the
  answer, so it is never raised from `response` — a caller who wants it
  programmatically reads `ResponseStream.cleanup_errors`, and a caller
  who wants it fatal runs with `-W error::lm15.errors.StreamCleanupWarning`.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "StreamCleanupWarning"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `args` (term())
  - `kwargs` (term())
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Add a note to the exception

  ## Parameters

  - `note` (term())

  ## Returns

  - `term()`
  """
  @spec add_note(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def add_note(ref, note, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :add_note, [note], opts)
  end

  @doc """
  Set self.__traceback__ to tb and return self.

  ## Parameters

  - `tb` (term())

  ## Returns

  - `term()`
  """
  @spec with_traceback(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def with_traceback(ref, tb, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :with_traceback, [tb], opts)
  end

  @spec args(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def args(ref) do
    SnakeBridge.Runtime.get_attr(ref, :args)
  end
end
