# Generated by SnakeBridge v0.18.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: TextDelta

defmodule Dspy.Lm15.TextDelta do
  @moduledoc """
  A text fragment arriving during streaming.

  `logprobs` carries the token logprobs for exactly the tokens in this
  fragment, when the request asked for them (`Config.logprobs`) and the
  provider streams them per chunk (verified live for OpenAI Responses,
  2026-09-01). Materialization concatenates fragment logprobs in arrival
  order into `Response.logprobs`. `logprobs_complete=False` means
  local text editing left some retained text without its original score
  (for example, a stop inside a token). Scores always describe original,
  whole provider tokens. True does not promise the provider supplied any.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "TextDelta"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `text` (String.t())
  - `part_index` (integer() default: 0)
  - `logprobs` ({term(), term()} default: ())
  - `logprobs_complete` (boolean() keyword-only default: True)
  """
  @spec new(String.t()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), integer()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), integer(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), integer(), {term(), term()}) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), integer(), {term(), term()}, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(text) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text], [])
  end

  def new(text, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text], opts)
  end

  def new(text, part_index) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, part_index], [])
  end

  def new(text, part_index, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, part_index], opts)
  end

  def new(text, part_index, logprobs) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, part_index, logprobs], [])
  end

  def new(text, part_index, logprobs, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [text, part_index, logprobs], opts)
  end

  @spec logprobs(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logprobs(ref) do
    SnakeBridge.Runtime.get_attr(ref, :logprobs)
  end

  @spec logprobs_complete(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logprobs_complete(ref) do
    SnakeBridge.Runtime.get_attr(ref, :logprobs_complete)
  end

  @spec part_index(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def part_index(ref) do
    SnakeBridge.Runtime.get_attr(ref, :part_index)
  end

  @spec text(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def text(ref) do
    SnakeBridge.Runtime.get_attr(ref, :text)
  end

  @spec type(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def type(ref) do
    SnakeBridge.Runtime.get_attr(ref, :type)
  end
end
