# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: TopLogprob

defmodule Dspy.Lm15.TopLogprob do
  @moduledoc """
  One scored alternative token at a decoding step.

  `bytes` is the token's UTF-8 byte sequence when the provider reports
  it (OpenAI); `token_id` is the vocabulary id when the provider
  reports it (Gemini).  Absence means "not reported", never zero.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "TopLogprob"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `token` (String.t())
  - `logprob` (float())
  - `bytes` ({integer(), term()} | nil default: None)
  - `token_id` (integer() | nil default: None)
  """
  @spec new(String.t(), float()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), float(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), float(), {integer(), term()} | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), float(), {integer(), term()} | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), float(), {integer(), term()} | nil, integer() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), float(), {integer(), term()} | nil, integer() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(token, logprob) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [token, logprob], [])
  end

  def new(token, logprob, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [token, logprob], opts)
  end

  def new(token, logprob, bytes) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [token, logprob, bytes], [])
  end

  def new(token, logprob, bytes, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [token, logprob, bytes], opts)
  end

  def new(token, logprob, bytes, token_id) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [token, logprob, bytes, token_id], [])
  end

  def new(token, logprob, bytes, token_id, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [token, logprob, bytes, token_id], opts)
  end

  @spec bytes(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def bytes(ref) do
    SnakeBridge.Runtime.get_attr(ref, :bytes)
  end

  @spec logprob(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def logprob(ref) do
    SnakeBridge.Runtime.get_attr(ref, :logprob)
  end

  @spec token(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def token(ref) do
    SnakeBridge.Runtime.get_attr(ref, :token)
  end

  @spec token_id(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def token_id(ref) do
    SnakeBridge.Runtime.get_attr(ref, :token_id)
  end
end
