# Generated by SnakeBridge v0.18.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: Usage

defmodule Dspy.Lm15.Usage do
  @moduledoc """
  Token usage.

  `input_tokens` and `output_tokens` are common dimensions.
  `total_tokens` is the provider-reported or billed total when present;
  providers may include reasoning, audio, cache, or future token classes in
  totals differently, so it is not forced to equal input + output.

  `reasoning_tokens` is populated only when the provider reports an exact
  separate reasoning/thinking token count. Some providers, notably Anthropic,
  can return `ThinkingPart` content while reporting only combined
  `output_tokens`; in that case `reasoning_tokens` remains `None`.

  Every counter is `int | None`: `None` means "the provider did not
  report this dimension", which is distinct from a reported `0`.
  `Usage()` with no arguments therefore means "nothing reported" and
  serializes to `{}` (omitted entirely by enclosing serializers, per
  docs/serde-rules.md).

  `total_tokens`: an explicit value is preserved as provider telemetry.
  When omitted, it auto-computes as `input_tokens + output_tokens` only
  when BOTH are present; if either is `None` the total stays `None`.

  Arithmetic over usage (e.g. `InferencePricing.estimate`) must treat
  `None` as "unknown", never as zero.

  Counters are provider-verbatim (spec/types.md, Usage, 2026-09-02): the
  same field means different things across providers. `input_tokens`
  includes cached tokens on OpenAI, Gemini, and xAI but not on Anthropic
  (whose cache counters are disjoint); `output_tokens` includes
  reasoning on OpenAI and Anthropic but not on Gemini and xAI. lm15 does
  not normalise: that is what a bill reconciles against. A consumer
  comparing across providers must apply the provider's rule from the
  table in the spec; `Response.provider_data` and the router's
  resolution say which provider answered.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "Usage"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `input_tokens` (integer() | nil default: None)
  - `output_tokens` (integer() | nil default: None)
  - `total_tokens` (integer() | nil default: None)
  - `cache_read_tokens` (integer() | nil default: None)
  - `cache_write_tokens` (integer() | nil default: None)
  - `reasoning_tokens` (integer() | nil default: None)
  - `input_audio_tokens` (integer() | nil default: None)
  - `output_audio_tokens` (integer() | nil default: None)
  """
  @spec new() :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil, integer() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil, integer() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil, integer() | nil, integer() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil, integer() | nil, integer() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(integer() | nil, integer() | nil, integer() | nil, integer() | nil, integer() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          integer() | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new() do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], [])
  end

  def new(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  def new(input_tokens) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [input_tokens], [])
  end

  def new(input_tokens, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [input_tokens], opts)
  end

  def new(input_tokens, output_tokens) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [input_tokens, output_tokens], [])
  end

  def new(input_tokens, output_tokens, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [input_tokens, output_tokens], opts)
  end

  def new(input_tokens, output_tokens, total_tokens) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [input_tokens, output_tokens, total_tokens],
      []
    )
  end

  def new(input_tokens, output_tokens, total_tokens, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [input_tokens, output_tokens, total_tokens],
      opts
    )
  end

  def new(input_tokens, output_tokens, total_tokens, cache_read_tokens) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [input_tokens, output_tokens, total_tokens, cache_read_tokens],
      []
    )
  end

  def new(input_tokens, output_tokens, total_tokens, cache_read_tokens, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [input_tokens, output_tokens, total_tokens, cache_read_tokens],
      opts
    )
  end

  def new(input_tokens, output_tokens, total_tokens, cache_read_tokens, cache_write_tokens) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [input_tokens, output_tokens, total_tokens, cache_read_tokens, cache_write_tokens],
      []
    )
  end

  def new(input_tokens, output_tokens, total_tokens, cache_read_tokens, cache_write_tokens, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [input_tokens, output_tokens, total_tokens, cache_read_tokens, cache_write_tokens],
      opts
    )
  end

  def new(
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens
      ) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens
      ],
      []
    )
  end

  def new(
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        opts
      )
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens
      ],
      opts
    )
  end

  def new(
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens
      ) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens
      ],
      []
    )
  end

  def new(
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens,
        opts
      )
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens
      ],
      opts
    )
  end

  def new(
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens,
        output_audio_tokens
      ) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens,
        output_audio_tokens
      ],
      []
    )
  end

  def new(
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens,
        output_audio_tokens,
        opts
      )
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [
        input_tokens,
        output_tokens,
        total_tokens,
        cache_read_tokens,
        cache_write_tokens,
        reasoning_tokens,
        input_audio_tokens,
        output_audio_tokens
      ],
      opts
    )
  end

  @spec cache_read_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache_read_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :cache_read_tokens)
  end

  @spec cache_write_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def cache_write_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :cache_write_tokens)
  end

  @spec input_audio_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def input_audio_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :input_audio_tokens)
  end

  @spec input_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def input_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :input_tokens)
  end

  @spec output_audio_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def output_audio_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :output_audio_tokens)
  end

  @spec output_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def output_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :output_tokens)
  end

  @spec reasoning_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def reasoning_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :reasoning_tokens)
  end

  @spec total_tokens(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def total_tokens(ref) do
    SnakeBridge.Runtime.get_attr(ref, :total_tokens)
  end
end
