# Generated by SnakeBridge v0.18.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.lm15
# Python class: VideoGenerationRequest

defmodule Dspy.Lm15.VideoGenerationRequest do
  @moduledoc """
  Text (and optionally an input image) in; a video JOB out.

  Video is job-shaped on every wire that sells it (Sora, Veo,
  grok-imagine): submission returns a ticket, not bytes.  `seconds`
  maps to the provider's duration knob and raises where the wire has
  none; `images` are input frames (image-to-video), ordinary
  ImageParts.
  """
  def __snakebridge_python_name__, do: "dspy.lm15"
  def __snakebridge_python_class__, do: "VideoGenerationRequest"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `model` (String.t())
  - `prompt` (String.t())
  - `seconds` (integer() | nil default: None)
  - `images` ({term(), term()} default: ())
  - `extensions` (%{
    optional(String.t()) =>
      (((((nil | boolean()) | integer()) | float()) | String.t())
       | list(
           (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
           | %{optional(String.t()) => term()}
         ))
      | %{
          optional(String.t()) =>
            (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
            | %{optional(String.t()) => term()}
        }
  }
  | nil default: None)
  """
  @spec new(String.t(), String.t()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), integer() | nil) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), integer() | nil, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), integer() | nil, {term(), term()}) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(String.t(), String.t(), integer() | nil, {term(), term()}, keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          String.t(),
          integer() | nil,
          {term(), term()},
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          }
          | nil
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(
          String.t(),
          String.t(),
          integer() | nil,
          {term(), term()},
          %{
            optional(String.t()) =>
              (((((nil | boolean()) | integer()) | float()) | String.t())
               | list(
                   (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                   | %{optional(String.t()) => term()}
                 ))
              | %{
                  optional(String.t()) =>
                    (((((nil | boolean()) | integer()) | float()) | String.t()) | list(term()))
                    | %{optional(String.t()) => term()}
                }
          }
          | nil,
          keyword()
        ) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(model, prompt) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, prompt], [])
  end

  def new(model, prompt, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, prompt], opts)
  end

  def new(model, prompt, seconds) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, prompt, seconds], [])
  end

  def new(model, prompt, seconds, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, prompt, seconds], opts)
  end

  def new(model, prompt, seconds, images) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, prompt, seconds, images], [])
  end

  def new(model, prompt, seconds, images, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [model, prompt, seconds, images], opts)
  end

  def new(model, prompt, seconds, images, extensions) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [model, prompt, seconds, images, extensions],
      []
    )
  end

  def new(model, prompt, seconds, images, extensions, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(
      __MODULE__,
      :__init__,
      [model, prompt, seconds, images, extensions],
      opts
    )
  end

  @spec extensions(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def extensions(ref) do
    SnakeBridge.Runtime.get_attr(ref, :extensions)
  end

  @spec images(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def images(ref) do
    SnakeBridge.Runtime.get_attr(ref, :images)
  end

  @spec model(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def model(ref) do
    SnakeBridge.Runtime.get_attr(ref, :model)
  end

  @spec prompt(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def prompt(ref) do
    SnakeBridge.Runtime.get_attr(ref, :prompt)
  end

  @spec seconds(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def seconds(ref) do
    SnakeBridge.Runtime.get_attr(ref, :seconds)
  end
end
