# Generated by SnakeBridge v0.13.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.clients.utils_finetune

defmodule Dspy.Clients.UtilsFinetune do
  @moduledoc """
  Submodule bindings for `dspy.clients.utils_finetune`.

  ## Version

  - Requested: 3.1.2
  - Observed at generation: 3.1.2

  ## Runtime Options

  All functions accept a `__runtime__` option for controlling execution behavior:

      Dspy.Clients.UtilsFinetune.some_function(args, __runtime__: [timeout: 120_000])

  ### Supported runtime options

  - `:timeout` - Call timeout in milliseconds (default: 120,000ms / 2 minutes)
  - `:timeout_profile` - Use a named profile (`:default`, `:ml_inference`, `:batch_job`, `:streaming`)
  - `:stream_timeout` - Timeout for streaming operations (default: 1,800,000ms / 30 minutes)
  - `:session_id` - Override the session ID for this call
  - `:pool_name` - Target a specific Snakepit pool (multi-pool setups)
  - `:affinity` - Override session affinity (`:hint`, `:strict_queue`, `:strict_fail_fast`)

  ### Timeout Profiles

  - `:default` - 2 minute timeout for regular calls
  - `:ml_inference` - 10 minute timeout for ML/LLM workloads
  - `:batch_job` - Unlimited timeout for long-running jobs
  - `:streaming` - 2 minute timeout, 30 minute stream_timeout

  ### Example with timeout override

      # For a long-running ML inference call
      Dspy.Clients.UtilsFinetune.predict(data, __runtime__: [timeout_profile: :ml_inference])

      # Or explicit timeout
      Dspy.Clients.UtilsFinetune.predict(data, __runtime__: [timeout: 600_000])

      # Route to a pool and enforce strict affinity
      Dspy.Clients.UtilsFinetune.predict(data, __runtime__: [pool_name: :strict_pool, affinity: :strict_queue])

  See `SnakeBridge.Defaults` for global timeout configuration.

  """

  @doc false
  def __snakebridge_python_name__, do: "dspy.clients.utils_finetune"
  @doc false
  def __snakebridge_library__, do: "dspy"

  @doc """
  Python binding for `dspy.clients.utils_finetune.find_data_error_chat`.

  ## Parameters

  - `messages` (%{optional(String.t()) => term()})

  ## Returns

  - `term()`
  """
  @spec find_data_error_chat(%{optional(String.t()) => term()}, keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def find_data_error_chat(messages, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :find_data_error_chat, [messages], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.find_data_error_chat_message`.

  ## Parameters

  - `message` (%{optional(String.t()) => term()})

  ## Returns

  - `term()`
  """
  @spec find_data_error_chat_message(%{optional(String.t()) => term()}, keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def find_data_error_chat_message(message, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :find_data_error_chat_message, [message], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.find_data_errors_completion`.

  ## Parameters

  - `data_dict` (%{optional(String.t()) => String.t()})

  ## Returns

  - `term()`
  """
  @spec find_data_errors_completion(%{optional(String.t()) => String.t()}, keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def find_data_errors_completion(data_dict, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :find_data_errors_completion, [data_dict], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.get_finetune_directory`.

  ## Returns

  - `String.t()`
  """
  @spec get_finetune_directory(keyword()) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def get_finetune_directory(opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :get_finetune_directory, [], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.infer_data_format`.

  ## Parameters

  - `adapter` (Dspy.Adapters.Base.Adapter.t())

  ## Returns

  - `String.t()`
  """
  @spec infer_data_format(Dspy.Adapters.Base.Adapter.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def infer_data_format(adapter, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :infer_data_format, [adapter], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.save_data`.

  ## Parameters

  - `data` (list(%{optional(String.t()) => term()}))

  ## Returns

  - `String.t()`
  """
  @spec save_data(list(%{optional(String.t()) => term()}), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def save_data(data, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :save_data, [data], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.validate_data_format`.

  ## Parameters

  - `data` (list(%{optional(String.t()) => term()}))
  - `data_format` (Dspy.Clients.UtilsFinetune.TrainDataFormat.t())

  ## Returns

  - `term()`
  """
  @spec validate_data_format(
          list(%{optional(String.t()) => term()}),
          Dspy.Clients.UtilsFinetune.TrainDataFormat.t(),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def validate_data_format(data, data_format, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :validate_data_format, [data, data_format], opts)
  end

  @doc """
  Python binding for `dspy.clients.utils_finetune.write_lines`.

  ## Parameters

  - `file_path` (term())
  - `data` (term())

  ## Returns

  - `term()`
  """
  @spec write_lines(term(), term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def write_lines(file_path, data, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :write_lines, [file_path, data], opts)
  end
end
