# Generated by SnakeBridge v0.18.1 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.clients.engines
# Python class: LM15Engine

defmodule Dspy.Clients.Engines.LM15Engine do
  @moduledoc """
  One synchronous native attempt. Close after its active calls finish.
  """
  def __snakebridge_python_name__, do: "dspy.clients.engines"
  def __snakebridge_python_class__, do: "LM15Engine"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `config` (term() | nil default: None)
  - `model_type` (term() keyword-only default: 'chat')
  """
  @spec new() :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term() | nil) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  @spec new(term() | nil, keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new() do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], [])
  end

  def new(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  def new(config) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [config], [])
  end

  def new(config, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [config], opts)
  end

  @doc """
  Execution backends for DSPy's LM layer.

  The outer LM layer selects these engines and owns caching, retries, fan-out
  and bookkeeping. No engine silently delegates a failed request to another
  backend.

  ## Parameters

  - `config` (term())
  - `model_type` (term())

  ## Returns

  - `term()`
  """
  @spec _init_routing(SnakeBridge.Ref.t(), term(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _init_routing(ref, config, model_type, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_init_routing, [config, model_type], opts)
  end

  @doc """
  Execution backends for DSPy's LM layer.

  The outer LM layer selects these engines and owns caching, retries, fan-out
  and bookkeeping. No engine silently delegates a failed request to another
  backend.

  ## Parameters

  - `request` (term())
  - `streaming` (term() keyword-only default: False)

  ## Returns

  - `term()`
  """
  @spec _target(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _target(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_target, [request], opts)
  end

  @doc """
  Execution backends for DSPy's LM layer.

  The outer LM layer selects these engines and owns caching, retries, fan-out
  and bookkeeping. No engine silently delegates a failed request to another
  backend.

  ## Returns

  - `term()`
  """
  @spec close(SnakeBridge.Ref.t(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def close(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :close, [], opts)
  end

  @doc """
  Execution backends for DSPy's LM layer.

  The outer LM layer selects these engines and owns caching, retries, fan-out
  and bookkeeping. No engine silently delegates a failed request to another
  backend.

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec complete(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def complete(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :complete, [request], opts)
  end

  @doc """
  What this request WOULD adapt on its route (lm15 MAP-13), with no network.

  Offline like `resolve`: no credential is read or invoked, so a
  model with no key configured still plans. Raises the refusal the
  call would raise, so engine selection can fall back before any I/O
  instead of after a failed attempt.

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec plan(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def plan(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :plan, [request], opts)
  end

  @doc """
  Offline routing. Callers inspect canonical errors, not a wrapped cause.

  ## Parameters

  - `model` (String.t())

  ## Returns

  - `term()`
  """
  @spec resolve(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def resolve(ref, model, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :resolve, [model], opts)
  end

  @doc """
  Execution backends for DSPy's LM layer.

  The outer LM layer selects these engines and owns caching, retries, fan-out
  and bookkeeping. No engine silently delegates a failed request to another
  backend.

  ## Parameters

  - `request` (term())

  ## Returns

  - `term()`
  """
  @spec stream(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def stream(ref, request, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :stream, [request], opts)
  end
end
