# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt
# Python class: BetterTogether

defmodule Dspy.Teleprompt.BetterTogether do
  def __snakebridge_python_name__, do: "dspy.teleprompt"
  def __snakebridge_python_class__, do: "BetterTogether"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @spec new(term(), list(term()), keyword()) ::
          {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(metric, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [metric] ++ List.wrap(args), opts)
  end

  @spec _compile_prompt_optimizer(SnakeBridge.Ref.t(), term(), term(), term(), keyword()) ::
          {:ok, Dspy.Primitives.Module.Module.t()} | {:error, Snakepit.Error.t()}
  def _compile_prompt_optimizer(ref, student, trainset, valset_ratio, opts \\ []) do
    SnakeBridge.Runtime.call_method(
      ref,
      :_compile_prompt_optimizer,
      [student, trainset, valset_ratio],
      opts
    )
  end

  @spec _compile_weight_optimizer(SnakeBridge.Ref.t(), term(), term(), keyword()) ::
          {:ok, Dspy.Primitives.Module.Module.t()} | {:error, Snakepit.Error.t()}
  def _compile_weight_optimizer(ref, student, trainset, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_compile_weight_optimizer, [student, trainset], opts)
  end

  @spec _run_strategies(SnakeBridge.Ref.t(), term(), term(), term(), term(), keyword()) ::
          {:ok, Dspy.Primitives.Module.Module.t()} | {:error, Snakepit.Error.t()}
  def _run_strategies(ref, parsed_strategy, student, trainset, valset_ratio, opts \\ []) do
    SnakeBridge.Runtime.call_method(
      ref,
      :_run_strategies,
      [parsed_strategy, student, trainset, valset_ratio],
      opts
    )
  end

  @spec compile(
          SnakeBridge.Ref.t(),
          Dspy.Primitives.Module.Module.t(),
          list(Dspy.Primitives.Example.t()),
          list(term()),
          keyword()
        ) :: {:ok, Dspy.Primitives.Module.Module.t()} | {:error, Snakepit.Error.t()}
  def compile(ref, student, trainset, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :compile, [student, trainset] ++ List.wrap(args), opts)
  end

  @spec get_params(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, %{optional(String.t()) => term()}} | {:error, Snakepit.Error.t()}
  def get_params(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_params, [], opts)
  end

  @spec strat_sep(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def strat_sep(ref) do
    SnakeBridge.Runtime.get_attr(ref, :STRAT_SEP)
  end
end
