# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.utils.hasher
# Python class: Hasher

defmodule Dspy.Utils.Hasher do
  def __snakebridge_python_name__, do: "dspy.utils.hasher"
  def __snakebridge_python_class__, do: "Hasher"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @spec hash(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def hash(ref, value, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :hash, [value], opts)
  end

  @spec hash_bytes(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def hash_bytes(ref, value, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :hash_bytes, [value], opts)
  end

  @spec hexdigest(SnakeBridge.Ref.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def hexdigest(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :hexdigest, [], opts)
  end

  @spec update(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def update(ref, value, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :update, [value], opts)
  end

  @spec dispatch(SnakeBridge.Ref.t()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dispatch(ref) do
    SnakeBridge.Runtime.get_attr(ref, :dispatch)
  end
end
