# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.utils

defmodule Dspy.Utils do
  @moduledoc """
  Submodule bindings for `dspy.utils`.
  """

  def __snakebridge_python_name__, do: "dspy.utils"
  def __snakebridge_library__, do: "dspy"

  @doc """

  """
  @spec download(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def download(url, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :download, [url], opts)
  end

  @doc """

  """
  @spec dummy_rm() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec dummy_rm(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec dummy_rm(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec dummy_rm(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def dummy_rm() do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [], [])
  end

  def dummy_rm(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [], opts)
  end

  def dummy_rm(passages) do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [passages], [])
  end

  def dummy_rm(passages, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :dummy_rm, [passages], opts)
  end

  @doc """
  Decorator / decorator creator for marking APIs experimental in the docstring.



  ## Parameters

  - `f` - The function to be decorated.
  - `version` - The version in which the API was introduced as experimental. The version is used to determine whether the API should be considered as stable or not when releasing a new version of DSPy.

  Parameters:
  - `f` (term() | nil default: None)
  - `version` (term() default: None)

  Returns:
  - `term()`
  """
  @spec experimental() :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec experimental(keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec experimental(term() | nil) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec experimental(term() | nil, keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec experimental(term() | nil, term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec experimental(term() | nil, term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def experimental() do
    SnakeBridge.Runtime.call(__MODULE__, :experimental, [], [])
  end

  def experimental(opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :experimental, [], opts)
  end

  def experimental(f) do
    SnakeBridge.Runtime.call(__MODULE__, :experimental, [f], [])
  end

  def experimental(f, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :experimental, [f], opts)
  end

  def experimental(f, version) do
    SnakeBridge.Runtime.call(__MODULE__, :experimental, [f, version], [])
  end

  def experimental(f, version, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :experimental, [f, version], opts)
  end

  @doc """
  Prints the last n prompts and their completions.

  Parameters:
  - `history` (term())
  - `n` (integer() default: 1)

  Returns:
  - `term()`
  """
  @spec pretty_print_history(term()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec pretty_print_history(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec pretty_print_history(term(), integer()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  @spec pretty_print_history(term(), integer(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def pretty_print_history(history) do
    SnakeBridge.Runtime.call(__MODULE__, :pretty_print_history, [history], [])
  end

  def pretty_print_history(history, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :pretty_print_history, [history], opts)
  end

  def pretty_print_history(history, n) do
    SnakeBridge.Runtime.call(__MODULE__, :pretty_print_history, [history, n], [])
  end

  def pretty_print_history(history, n, opts)
      when is_list(opts) and
             (opts == [] or
                (is_tuple(hd(opts)) and tuple_size(hd(opts)) == 2 and is_atom(elem(hd(opts), 0)))) do
    SnakeBridge.Runtime.call(__MODULE__, :pretty_print_history, [history, n], opts)
  end

  @doc """
  Decorator to add callback functionality to instance methods.

  Parameters:
  - `fn` (term())

  Returns:
  - `term()`
  """
  @spec with_callbacks(term(), keyword()) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def with_callbacks(py_fn, opts \\ []) do
    SnakeBridge.Runtime.call(__MODULE__, :with_callbacks, [py_fn], opts)
  end
end
