# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.predict.avatar.models

defmodule Dspy.Predict.Avatar.Models do
  @moduledoc """
  Submodule bindings for `dspy.predict.avatar.models`.
  """

  def __snakebridge_python_name__, do: "dspy.predict.avatar.models"
  def __snakebridge_library__, do: "dspy"
end
