# Generated by SnakeBridge v0.17.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.4.0
# Python module: dspy.primitives
# Python class: LocalInterpreter

defmodule Dspy.Primitives.LocalInterpreter do
  @moduledoc """
  Execute Python in a persistent local subprocess.

  This separates generated code from DSPy's memory, stdout, and lifecycle,
  but it is not a security sandbox. The worker retains the host user's files,
  environment, credentials, subprocess, and network authority.

  ## Parameters

  - `tools` - Host functions exposed to executed code by name. Arguments and return values must be JSON-compatible.
  - `output_fields` - Optional field definitions for typed `SUBMIT` calls.
  - `execution_timeout` - Maximum seconds for one execution, including host tool calls. A timeout terminates the worker and its session state. Python cannot forcibly stop a running host callable, so a timed-out callable may finish in a detached daemon thread; its result is discarded.
  - `callbacks` - Optional instance-level callback handlers.
  """
  def __snakebridge_python_name__, do: "dspy.primitives"
  def __snakebridge_python_class__, do: "LocalInterpreter"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @doc """
  Initialize self.  See help(type(self)) for accurate signature.

  ## Parameters

  - `tools` (%{optional(String.t()) => term()} | nil default: None)
  - `output_fields` (list(%{optional(String.t()) => term()}) | nil default: None)
  - `execution_timeout` (float() | nil keyword-only default: None)
  - `callbacks` (list(term()) | nil keyword-only default: None)
  """
  @spec new(list(term()), keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [] ++ List.wrap(args), opts)
  end

  @doc """
  Python method `LocalInterpreter._handle_tool`.

  ## Parameters

  - `request` (%{optional(String.t()) => term()})
  - `process` (term())

  ## Returns

  - `nil`
  """
  @spec _handle_tool(SnakeBridge.Ref.t(), %{optional(String.t()) => term()}, term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _handle_tool(ref, request, process, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_handle_tool, [request, process], opts)
  end

  @doc """
  Python method `LocalInterpreter._kill`.

  ## Returns

  - `nil`
  """
  @spec _kill(SnakeBridge.Ref.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def _kill(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_kill, [], opts)
  end

  @doc """
  Python method `LocalInterpreter._raise_terminal_error`.

  ## Parameters

  - `message` (String.t())
  - `cause` (term() | nil default: None)

  ## Returns

  - `term()`
  """
  @spec _raise_terminal_error(SnakeBridge.Ref.t(), String.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def _raise_terminal_error(ref, message, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_method(
      ref,
      :_raise_terminal_error,
      [message] ++ List.wrap(args),
      opts
    )
  end

  @doc """
  Python method `LocalInterpreter._read_responses`.

  ## Parameters

  - `process` (term())

  ## Returns

  - `nil`
  """
  @spec _read_responses(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _read_responses(ref, process, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_read_responses, [process], opts)
  end

  @doc """
  Python method `LocalInterpreter._receive`.

  ## Parameters

  - `deadline` (float() | nil)
  - `timeout_message` (String.t())

  ## Returns

  - `%{optional(String.t()) => term()}`
  """
  @spec _receive(SnakeBridge.Ref.t(), float() | nil, String.t(), keyword()) ::
          {:ok, %{optional(String.t()) => term()}} | {:error, Snakepit.Error.t()}
  def _receive(ref, deadline, timeout_message, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_receive, [deadline, timeout_message], opts)
  end

  @doc """
  Python method `LocalInterpreter._send`.

  ## Parameters

  - `message` (%{optional(String.t()) => term()})
  - `process` (term() | nil default: None)

  ## Returns

  - `nil`
  """
  @spec _send(SnakeBridge.Ref.t(), %{optional(String.t()) => term()}, list(term()), keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _send(ref, message, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :_send, [message] ++ List.wrap(args), opts)
  end

  @doc """
  Python method `LocalInterpreter._validate_output_fields`.

  ## Parameters

  - `output_fields` (list(%{optional(String.t()) => term()}) | nil)

  ## Returns

  - `nil`
  """
  @spec _validate_output_fields(
          SnakeBridge.Ref.t(),
          list(%{optional(String.t()) => term()}) | nil,
          keyword()
        ) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def _validate_output_fields(ref, output_fields, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_validate_output_fields, [output_fields], opts)
  end

  @doc """
  Python method `LocalInterpreter._validate_tool_names`.

  ## Parameters

  - `tools` (%{optional(String.t()) => term()})

  ## Returns

  - `nil`
  """
  @spec _validate_tool_names(SnakeBridge.Ref.t(), %{optional(String.t()) => term()}, keyword()) ::
          {:ok, nil} | {:error, Snakepit.Error.t()}
  def _validate_tool_names(ref, tools, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_validate_tool_names, [tools], opts)
  end

  @doc """
  Execute code in the worker's persistent namespace.

  ## Parameters

  - `code` (String.t())
  - `variables` (%{optional(String.t()) => term()} | nil default: None)

  ## Returns

  - `term()`
  """
  @spec execute(SnakeBridge.Ref.t(), String.t(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def execute(ref, code, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :execute, [code] ++ List.wrap(args), opts)
  end

  @doc """
  Invoke one currently registered host tool.

  ## Parameters

  - `tool_name` (String.t())
  - `args` (list(term()))
  - `kwargs` (%{optional(String.t()) => term()})

  ## Returns

  - `term()`
  """
  @spec invoke_tool(
          SnakeBridge.Ref.t(),
          String.t(),
          list(term()),
          %{optional(String.t()) => term()},
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def invoke_tool(ref, tool_name, args, kwargs, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :invoke_tool, [tool_name, args, kwargs], opts)
  end

  @doc """
  Terminate the worker and discard its session state.

  ## Returns

  - `nil`
  """
  @spec shutdown(SnakeBridge.Ref.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def shutdown(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :shutdown, [], opts)
  end

  @doc """
  Start the worker, or return immediately if it is already running.

  ## Returns

  - `nil`
  """
  @spec start(SnakeBridge.Ref.t(), keyword()) :: {:ok, nil} | {:error, Snakepit.Error.t()}
  def start(ref, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :start, [], opts)
  end

  @spec execution_instructions(SnakeBridge.Ref.t()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def execution_instructions(ref) do
    SnakeBridge.Runtime.get_attr(ref, :execution_instructions)
  end
end
