# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.clients.openai

defmodule Dspy.Clients.Openai do
  @moduledoc """
  Submodule bindings for `dspy.clients.openai`.
  """

  def __snakebridge_python_name__, do: "dspy.clients.openai"
  def __snakebridge_library__, do: "dspy"
end
