# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.clients.openai
# Python class: OpenAIProvider

defmodule Dspy.Clients.Openai.OpenAIProvider do
  def __snakebridge_python_name__, do: "dspy.clients.openai"
  def __snakebridge_python_class__, do: "OpenAIProvider"
  def __snakebridge_library__, do: "dspy"
  @opaque t :: SnakeBridge.Ref.t()

  @spec new(keyword()) :: {:ok, SnakeBridge.Ref.t()} | {:error, Snakepit.Error.t()}
  def new(opts \\ []) do
    SnakeBridge.Runtime.call_class(__MODULE__, :__init__, [], opts)
  end

  @spec _remove_provider_prefix(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def _remove_provider_prefix(ref, model, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :_remove_provider_prefix, [model], opts)
  end

  @spec _start_remote_training(
          SnakeBridge.Ref.t(),
          String.t(),
          String.t(),
          list(term()),
          keyword()
        ) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def _start_remote_training(ref, train_file_id, model, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_method(
      ref,
      :_start_remote_training,
      [train_file_id, model] ++ List.wrap(args),
      opts
    )
  end

  @spec does_file_exist(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def does_file_exist(ref, file_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :does_file_exist, [file_id], opts)
  end

  @spec does_job_exist(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def does_job_exist(ref, job_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :does_job_exist, [job_id], opts)
  end

  @spec finetune(
          SnakeBridge.Ref.t(),
          Dspy.Clients.Openai.TrainingJobOpenAI.t(),
          String.t(),
          list(%{optional(String.t()) => term()}),
          term(),
          list(term()),
          keyword()
        ) :: {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def finetune(ref, job, model, train_data, train_data_format, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)

    SnakeBridge.Runtime.call_method(
      ref,
      :finetune,
      [job, model, train_data, train_data_format] ++ List.wrap(args),
      opts
    )
  end

  @spec get_trained_model(SnakeBridge.Ref.t(), term(), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def get_trained_model(ref, job, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_trained_model, [job], opts)
  end

  @spec get_training_status(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, Dspy.Clients.UtilsFinetune.TrainingStatus.t()} | {:error, Snakepit.Error.t()}
  def get_training_status(ref, job_id, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :get_training_status, [job_id], opts)
  end

  @spec is_provider_model(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def is_provider_model(ref, model, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :is_provider_model, [model], opts)
  end

  @spec is_terminal_training_status(
          SnakeBridge.Ref.t(),
          Dspy.Clients.UtilsFinetune.TrainingStatus.t(),
          keyword()
        ) :: {:ok, boolean()} | {:error, Snakepit.Error.t()}
  def is_terminal_training_status(ref, status, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :is_terminal_training_status, [status], opts)
  end

  @spec kill(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def kill(ref, lm, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :kill, [lm] ++ List.wrap(args), opts)
  end

  @spec launch(SnakeBridge.Ref.t(), term(), list(term()), keyword()) ::
          {:ok, term()} | {:error, Snakepit.Error.t()}
  def launch(ref, lm, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :launch, [lm] ++ List.wrap(args), opts)
  end

  @spec upload_data(SnakeBridge.Ref.t(), String.t(), keyword()) ::
          {:ok, String.t()} | {:error, Snakepit.Error.t()}
  def upload_data(ref, data_path, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :upload_data, [data_path], opts)
  end

  @spec validate_data_format(
          SnakeBridge.Ref.t(),
          Dspy.Clients.UtilsFinetune.TrainDataFormat.t(),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def validate_data_format(ref, data_format, opts \\ []) do
    SnakeBridge.Runtime.call_method(ref, :validate_data_format, [data_format], opts)
  end

  @spec wait_for_job(
          SnakeBridge.Ref.t(),
          Dspy.Clients.Openai.TrainingJobOpenAI.t(),
          list(term()),
          keyword()
        ) :: {:ok, term()} | {:error, Snakepit.Error.t()}
  def wait_for_job(ref, job, args, opts \\ []) do
    {args, opts} = SnakeBridge.Runtime.normalize_args_opts(args, opts)
    SnakeBridge.Runtime.call_method(ref, :wait_for_job, [job] ++ List.wrap(args), opts)
  end
end
