# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.teleprompt.bettertogether

defmodule Dspy.Teleprompt.Bettertogether do
  @moduledoc """
  Submodule bindings for `dspy.teleprompt.bettertogether`.
  """

  def __snakebridge_python_name__, do: "dspy.teleprompt.bettertogether"
  def __snakebridge_library__, do: "dspy"
end
