# Generated by SnakeBridge v0.12.0 - DO NOT EDIT MANUALLY
# Regenerate with: mix compile
# Library: dspy 3.1.2
# Python module: dspy.adapters.types.base_type

defmodule Dspy.Adapters.Types.BaseType do
  @moduledoc """
  Submodule bindings for `dspy.adapters.types.base_type`.
  """

  def __snakebridge_python_name__, do: "dspy.adapters.types.base_type"
  def __snakebridge_library__, do: "dspy"

  @doc """
  Split user message content into a list of content blocks.

  This method splits each user message's content in the `messages` list to be a list of content block, so that
  the custom types like `dspy.Image` can be properly formatted for better quality. For example, the split content
  may look like below if the user message has a `dspy.Image` object:

  ```
  [
    {"type": "text", "text": "{text_before_image}"},
    {"type": "image_url", "image_url": {"url": "{image_url}"}},
    {"type": "text", "text": "{text_after_image}"},
  ]
  ```

  This is implemented by finding the `<<CUSTOM-TYPE-START-IDENTIFIER>>` and `<<CUSTOM-TYPE-END-IDENTIFIER>>`
  in the user message content and splitting the content around them. The `<<CUSTOM-TYPE-START-IDENTIFIER>>`
  and `<<CUSTOM-TYPE-END-IDENTIFIER>>` are the reserved identifiers for the custom types as in `dspy.Type`.

  ## Parameters

  - `messages` - a list of messages sent to the LM. The format is the same as [OpenAI API's messages format](https://platform.openai.com/docs/guides/chat-completions/response-format).

  Parameters:
  - `messages` (list(%{optional(String.t()) => term()}))

  Returns:
  - `list(%{optional(String.t()) => term()})`
  """
  @spec split_message_content_for_custom_types(list(%{optional(String.t()) => term()}), keyword()) ::
          {:ok, list(%{optional(String.t()) => term()})} | {:error, Snakepit.Error.t()}
  def split_message_content_for_custom_types(messages, opts \\ []) do
    SnakeBridge.Runtime.call(
      __MODULE__,
      :split_message_content_for_custom_types,
      [messages],
      opts
    )
  end
end
